### ISSUE TITLE
FlowcharWindow causes GUI Layout error in the Unity 2021 LTS (Severe BUG!)

### ISSUE THREAD

**Issue by breadnone** [snozbot/fungus#1052]
**Describe the bug**
GUI Layout error will be thrown, every time there is an action in the Flowchart graph in Unity 2021 LTS and will cause StackOverflow exception.

**To Reproduce**
Install Fungus in Unity 2021 LTS, create a flowchart, then Open Flowchart Window. The error will be shown

**Additional context**
It's a very sever bug, almost makes Fungus unusable in projects!

**Comment by oldbloodgames** [comment]
Just seconding the issue. This bug essentially makes using Fungus in Unity 2021 impossible with the perpetual crashing from the StackOverflow exception.

**Comment by DrXand** [comment]
Same problem on any version of Unity 2021, LTS or not. Because of this, I can't migrate my project to the new version of the engine.

**Comment by addie-lombardo** [comment]
Was about to finally leave an issue for this and glad to see others have been seeing it too and it's not just me. I did do a quick run through the script and all the Begin/End methods are being called properly (which is what the error warns you about) so I'm at a little bit of a loss as to what changed in the change from 2020 to 2021. I'll dive deeper on this because it needs to be fixed, I'm sick of Unity regularly crashing!

**Comment by breadnone** [comment]
Found a fix for this, will make a pr soon

**Comment by stevehalliwell** [comment]
The linked pr seems straightforward enough. But can someone provide detailed repro steps for unity 2021.3.1 as I'm not able to create it other than as a one off when adding a variable to a flowchart via the in flowchartwindow add button. So we can go through the steps to check for other gremlins hiding in there.

**Comment by breadnone** [comment]
> The linked pr seems straightforward enough. But can someone provide detailed repro steps for unity 2021.3.1 as I'm not able to create it other than as a one off when adding a variable to a flowchart via the in flowchartwindow add button. So we can go through the steps to check for other gremlins hiding in there.

@stevehalliwell Another way to trigger the error is by clicking the flowchart gameObject in the hierarchy then click the `Open Flowchart Window`. Basically anything that triggers the opening of a flowchart would trigger it.

Another thing that CAN'T trigger the error is when the domain-reloading is done then very quickly(like immediately) open the flowchart window, we can sometimes open the flowchart window without any hiccups/issues
