### ISSUE TITLE
Game Pad support

### ISSUE THREAD

**Issue by RonanPearce** [snozbot/fungus#210]
Use a game pad controller to select menu options / click through dialogs.

Requested on [the forum](http://fungusgames.com/forum/#!/general:gamepad-support)

**Comment by chrisgregan** [comment]
Requested again on [the forum](http://fungusgames.com/forum/#!/support-questions:i-want-to-use-the-360-contr)

**Comment by chrisgregan** [comment]
Fixed in Fungus 3.0.0 #507
