### ISSUE TITLE
Define command list in spreadsheet

### ISSUE THREAD

**Issue by RonanPearce** [snozbot/fungus#224]
Allow users to define a sequence of commands in a spreadsheet and then execute the sequence using a Fungus command. We'll probably need to extend Fungus commands to expose a factory method which knows how to interpret the spreadsheet row data to populate the correct command parameters.

Requested by a user on Reddit
http://www.reddit.com/r/Unity3D/comments/353atm/fungus_our_free_opensource_plugin_for_unity_that/cr187za

As well as supporting spreadsheets, we should support data in xml and json formats.

**Comment by chrisgregan** [comment]
This has been implemented via Lua scripting.
