### ISSUE TITLE
Variable expression evaluation system

### ISSUE THREAD

**Issue by RonanPearce** [snozbot/fungus#233]
It should be possible to evaluate compound expressions like this in an if statement:
((PlayerName=="Chris" && Score==2) || (PlayerName=="John" && Score==4))

It would also be very powerful to be able to do this in an Event Handler. This is essentially rule based block selection as [described here](
http://fungusgames.com/forum/#!/support-questions:feature-request-rule-based)

**Comment by RonanPearce** [comment]
Requested on the forums: http://fungusgames.com/forum/#!/general:more-complex-ifthenandor

**Comment by chrisgregan** [comment]
This can now be done via Lua scripting. 
1. Use LuaBindings to bind a Flowchart component
2. Add an ExecuteLua command to evaluate the expression. Store the return value in a Boolean variable.
3. Add an If command which checks the value of the Boolean variable.

In the Execute Lua command, you use the Flowchart.GetVariable() method to get the variables to use in the expression. e.g. In Lua,

```
v1 = flowchart.GetVariable("VarName1").Value
v2 = flowchart.GetVariable("VarName2").Value

return v1 == v2
```
