### ISSUE TITLE
Drag and Drop event handler to support array of target objects

### ISSUE THREAD

**Issue by RonanPearce** [snozbot/fungus#238]
From the forums: "Would it be possible to add an array to the event targets involved in dragging and dropping? It would be nice, if I have 5 draggable objects, they all halt swipinng when being dragged, instead of having to create 5 different on drag start events."

"Maybe we could do something with GameObject variables. Like have the Event Handler take an array of game objects to work on, and a GameObject variable that will get populated when the event happens so that the commands in the block can act on it. I can see how it would be useful for complex drag and drop setups."

**Comment by SarveshBajaj** [comment]
I would like to work on the issue. Anything I should keep in mind during its implementation?

**Comment by SarveshBajaj** [comment]
Do I need an array/list for the targets (colliders) as well in drag completed, drag entered and drag exited events?

**Comment by stevehalliwell** [comment]
You'll probably want to add a draggableObjects[] array and use [HideInInspector] draggableObject. Then in OnValidate, move any ref from the single to the array for back compat.

I'd also add a FungusVariable reference to the event handlers, set that to the object that is causing the block to execute can be stored there for the block to access. There is no Draggable FungusVariable at the moment, so probably fall back to a GameObjectVariable.

I would do the same for the Drag EventHandlers that have targets too. Essientially making it, if any of these draggables, <verbs> any of these colliders, I'll save which two it was and call your block.

Given how much duplication there is among them, I'd be tempted to refactor much of it to a common abstract base, but its not required.

**Comment by SarveshBajaj** [comment]
InvalidOperationException: EnsureRunningOnMainThread can only be called from the main thread

Hi,for the above error, I have an alternate solution using awake() and [ExecuteAlways], so should I use this? Or, should I implement your solution? PR #791
