### ISSUE TITLE
Event handler that handles any built-in Unity event

### ISSUE THREAD

**Issue by RonanPearce** [snozbot/fungus#247]
We could add an Uber-event handler that can handle any of the built-in Unity events. The Unity Testing Tools have a component which works this way.  The idea would be to attach a listener component to the target object at startup and then have it callback to the Event Handler.

This is the list of methods from CheckMethod.cs

---
    public enum CheckMethod
    {
        AfterPeriodOfTime       = 1 << 0,
            Start                   = 1 << 1,
            Update                  = 1 << 2,
            FixedUpdate             = 1 << 3,
            LateUpdate              = 1 << 4,
            OnDestroy               = 1 << 5,
            OnEnable                = 1 << 6,
            OnDisable               = 1 << 7,
            OnControllerColliderHit = 1 << 8,
            OnParticleCollision     = 1 << 9,
            OnJointBreak            = 1 << 10,
            OnBecameInvisible       = 1 << 11,
            OnBecameVisible         = 1 << 12,
            OnTriggerEnter          = 1 << 13,
            OnTriggerExit           = 1 << 14,
            OnTriggerStay           = 1 << 15,
            OnCollisionEnter        = 1 << 16,
            OnCollisionExit         = 1 << 17,
            OnCollisionStay         = 1 << 18,
            OnTriggerEnter2D        = 1 << 19,
            OnTriggerExit2D         = 1 << 20,
            OnTriggerStay2D         = 1 << 21,
            OnCollisionEnter2D      = 1 << 22,
            OnCollisionExit2D       = 1 << 23,
            OnCollisionStay2D       = 1 << 24,
    }
---

**Comment by chrisgregan** [comment]
The new ExecuteHandler component does this.
