### ISSUE TITLE
Start executing a specific command from editor in play mode

### ISSUE THREAD

**Issue by chrisgregan** [snozbot/fungus#274]
Right click on a command in a non-executing block and select Execute from the menu to start execution from there. Very useful for testing during development.

Requested on [the forum](http://fungusgames.com/forum/#!/general:suggestion-flowchart-test)

**Comment by inarizushi** [comment]
I want to try working on this one. Here's the start of it: https://github.com/inarizushi/Fungus/commit/b5081a530b49095066eb411c3435e05a643e1ce4
Can you tell me if I'm on the right track or if you have a specific idea of how this should go? Thanks!

**Comment by inarizushi** [comment]
So this can be closed right? :)

**Comment by chrisgregan** [comment]
yup!
