### ISSUE TITLE
GameObjects get duplicated when flowchart is on a different scene

### ISSUE THREAD

**Issue by lucaslizama** [snozbot/fungus#373]
Greetings, I started using Unity 5.3 multi scene edit, I have my flowchart on a separate scene from, let's say, the GameObject I want to reference so I can Invoke methods from it or move it/rotate it/etc, when I press play, automatically all the referenced objects in the flowchart that are not in the same scene get duplicated to the flowchart's scene. The only workaround I have for now is moving the Gameobjects to the other scene before executing blocks but it's very counter intuitive.

For reference I'm using fungus as a dialogue system and sequencer for my game, It would be great if I could reference different scene GameObjects without the duplication thing.

**Comment by chrisgregan** [comment]
Yeah I've come across this, but I think it's a Unity-level issue?

Reading [the docs](http://docs.unity3d.com/Manual/MultiSceneEditing.html), there's this note at the end.
"Cross-scene references are not supported but also not prevented."

**Comment by chrisgregan** [comment]
Closing as this is the expected behavior in Unity.
