### ISSUE TITLE
Ignored commands "portrait"

### ISSUE THREAD

**Issue by KVinS** [snozbot/fungus#497]
If you very fast click on the text, the portraits will not appear. Text Only.
![2016-06-16_20-26-05](https://cloud.githubusercontent.com/assets/3009807/16126428/cd1d90cc-3400-11e6-8b1e-4e12cd9166e1.png)

**Comment by chrisgregan** [comment]
Sorry - missed this one.

I tried to replicate this in the Sherlock example but couldn't get it to happen. Can you try it in Sherlock and describe exactly what you do to get it happen. If I can replicate it I'll fix it!

**Comment by chrisgregan** [comment]
Closing this as I can't replicate it.
