### ISSUE TITLE
Fungus Lua not working in Web GL (Unity 5.4)

### ISSUE THREAD

**Issue by chrisgregan** [snozbot/fungus#525]
Reported on [the forum](http://fungusgames.com/forum/#!/general:fungus-lua-and-web-gl-uni)

**Comment by chrisgregan** [comment]
WebGL support seems to be broken in MoonSharp currently. I've posted [a question](https://groups.google.com/d/msg/moonsharp/iL0Rkh7RpiQ/IoiZUSCeEAAJ) on the MoonSharp forum to see if a fix is coming.

**Comment by StefanoCecere** [comment]
so, today, we can't release Fungus 3.0 adventures on the web/webgl, right?
or if we don't use any LUA they would work?

**Comment by chrisgregan** [comment]
Fungus works fine on WebGL if you don't use any Lua. It's just when you go to execute a Lua Script that WebGL breaks. The author of MoonSharp said he'll look at the issue again but no update yet.

**Comment by StefanoCecere** [comment]
no news with MoonSharp 1.8, right?

**Comment by kreys** [comment]
On MoonSharp forum the linked thread is marked as closed now:

"Xanathar on 14 Oct says:
Closing this thread : MoonSharp 2.0 works on webgl with no apparent issues."

So probably updating to MoonSharp 1.8 should resolve the issue.

**Comment by chrisgregan** [comment]
I'm trying out MoonSharp 2.0 now, so far so good. I've to do a bit of work around the Lua debugger (using VS code) but doesn't look too bad.

**Comment by chrisgregan** [comment]
Committed the fix for this today (upgraded to MoonSharp 2.0).
