### ISSUE TITLE
Block inspector displayed for inactive flowchart

### ISSUE THREAD

**Issue by chrisgregan** [snozbot/fungus#544]
Reported on [the forum](http://fungusgames.com/forum/#!/general:anyone-has-same-problem)

**Comment by AndyGFX** [comment]
Hi,

this bug is back with Unity 5.5.0 when is fungus gameobject as child under inactive parent.

**Comment by chrisgregan** [comment]
Thanks, will look into it.

**Comment by chrisgregan** [comment]
Ok, I tried to replicate this again and I can't get it to happen. 

Looking at your screenshot, I notice that FU-BLOCKS appears active in the hierarchy while the parent [Fungus] appears to be inactive. How is that possible? When I deactivate a parent in the hierarchy here it deactivates (dims) all the children automatically.

Internally, we're using the gameObject.activeInHierarchy property to check if the Flowchart is active or not and that call should take into account the state of all parent objects.

I notice you're using some 3rd party assets in the project. Do you get the same behaviour in a clean project without those assets?

**Comment by chrisgregan** [comment]
Can't replicate this issue
