### ISSUE TITLE
PODTypeFactory and FungusPrefs classes are not registered

### ISSUE THREAD

**Issue by ethan-tqa** [snozbot/fungus#549]
This issue is present if I just want to use FungusLua without the rest of Fungus. In LuaUtils.InitTypes(), all types in Fungus namespace are assumed to be unavaiable, which is not true in this case. This also mean that luautils.factory is not available for use. The same thing goes for FungusPrefs. I'm not sure what is the best solution here, so a quick patch is I have to manually insert `LuaEnvironment.RegisterType("Fungus.PODTypeFactory");`
before 
`fungusTable["factory"] = UserData.CreateStatic(typeof(PODTypeFactory));`

**Comment by ethan-tqa** [comment]
Oh and the document is incorrect, it should be 
`local a = factory.vector3(2, 3, 5)`
not
`local a = luautils.factory.vector3(2, 3, 5)`

**Comment by chrisgregan** [comment]
Thanks for the heads up, just committed a fix for these.
