### ISSUE TITLE
Drag Completed/Cancelled animation fail

### ISSUE THREAD

**Issue by fgoo** [snozbot/fungus#580]
Hi,

I was getting an issue with drag cancelled animation, some times the object didn't animate back in place.

I fixed on my way.. :)

**[DragCompleted.cs] - Added Return Value 1 or 0**
`public virtual int OnDragCompleted(Draggable2D draggableObject)
        {
            if (draggableObject == this.draggableObject && overTarget)
            {
                // Assume that the player will have to do perform another drag and drop operation
                // to complete the drag again. This is necessary because we don't get an OnDragExited if the
                // draggable object is set to be inactive.
                overTarget = false;
                ExecuteBlock();
		return 1;
            }
		return 0;
}`

**[Draggable2D.cs] - If Return 1 inside DoEndDrag() it is Completed**
`
ret = handler.OnDragCompleted (this);
if (ret == 1) {
	dragCompleted = true;
	if (returnOnCompleted) {
		LeanTween.move (gameObject, startingPosition, returnDuration).setEase(LeanTweenType.easeOutExpo);
	}
}
`

Thanks a lot for this Project..

**Comment by chrisgregan** [comment]
Thanks for the fix fgoo, will try to get it in for next release.

**Comment by chrisgregan** [comment]
Hmmm the code here has changed around due to another pull request. We're now using an EventDispatcher to send the DragCompletedEvent and there's no easy way to get a return value from that. 

I'm trying to understand what situation was causing the return animation not to trigger. What's the actual cause of the problem?

**Comment by fgoo** [comment]
Hello Chris, 
Sorry for the late answer.
The issue is intermittent, to simulate use mouse to start drag and release several times missing the target.
Some times the object does not return to place and start using this new position as its new place.
Regards,

**Comment by fgoo** [comment]
Hello Chris,
I couldn't reproduce the error in the new version of Fungus.
Think you can close this issue.

Regards,
