### ISSUE TITLE
Flowchart prefab's block show as empty on the Inspector in Unity 5.5 + Fungus 3.4.0

### ISSUE THREAD

**Issue by wrongtarget** [snozbot/fungus#583]
Create a Fungus Flowchart and it will show up on the scene.  
Select the Flowchart > Open Flowchart Window > Select New Block > Observe normal Block information on the inspector

![](http://i.imgur.com/h0npcH6.png)

Now make the flowchart a prefab and delete it from the scene. Select the Flowchart prefab > Open Flowchart Window > Select New Block > Observe empty Block information in the inspector

![](http://i.imgur.com/YHPufuV.png)

## Expected:

Prefab should behave the way the object does in the scene and show all the Inspector info.

**Comment by chrisgregan** [comment]
Nice one Claudio, thanks for the bug report!

**Comment by wrongtarget** [comment]
No worries! Actually Chris, the workaround doesn't work either. Fungus cannot access the changes I make to the object after converting it to prefab again. Thought that it was worth mentioning.

**Comment by chrisgregan** [comment]
Alrighty. I'm in bug fixing mode next week so should get a look at it then.
