### ISSUE TITLE
Spine integration is out of date

### ISSUE THREAD

**Issue by Bloodwork** [snozbot/fungus#585]
Here's a screenshot with Unity 5.5, Fungus 3.4 and the latest Spine runtimes: https://monosnap.com/file/QMqrhJhEf0wcm796jc8qZvU6OpFgrw

Please refer to this forum thread for more information: http://fungusgames.com/forum/#!/support-questions:spine-addon-error

**Comment by chrisgregan** [comment]
Thanks for the bug report. Looks like a change in the Spine runtimes, will update the integration code for the next release.

**Comment by Bloodwork** [comment]
Thank you! Any ETA for next release?

**Comment by chrisgregan** [comment]
I just wrapped up the new Save System which took a few weeks. Going through cleaning up bugs now which will prob take a few days then I'll make the release.

**Comment by chrisgregan** [comment]
Ok found the problem, it was change to the Spine runtime API. I've updated the integration Unity package, it'll be included in the next release.

In the meantime, you can download the new .unitypackage here:
https://github.com/snozbot/fungus/blob/master/Assets/Fungus/Integrations/Spine/Fungus-Spine.unitypackage
