### ISSUE TITLE
Custom Beeps keep playing into next dialog in Conversation

### ISSUE THREAD

**Issue by lealeelu** [snozbot/fungus#591]
I added a custom character sound effect to character 1. Then I made character 2 to act as the narrator with a custom narrator dialog box that is muted. When I have a dialog from character 1 and then have the silent narrator dialog, the sound effect from character 1 will play during character 2's dialog for a couple seconds. 
Here's an example of what I'm talking about: https://youtu.be/05CbzRkZn7s

It only seems to happen in the Conversation system. I tried to recreate the bug with two say dialogs and it had no problem.

**Comment by lealeelu** [comment]
I think I figured out where the problem is. We're setting the audio source here:
https://github.com/lealeelu/Fungus/blob/master/Assets/Fungus/Scripts/Components/WriterAudio.cs#L69
But when I change the dialog box being used, it still uses the audio source of that was first found, and not the active dialog's audio source.

**Comment by lealeelu** [comment]
That last comment might be relevant later, but wasn't the cause of my problem. I found out what was wrong and I'll be sending in a pull request soon.

**Comment by chrisgregan** [comment]
Thanks for looking into it Leah, should have time on Monday to review it
