### ISSUE TITLE
MenuDialog.IsActive() for undefined MenuDialog

### ISSUE THREAD

**Issue by Yamist** [snozbot/fungus#606]
When setting a menu option, I wanted my code to check if any menus were active in order to avoid running multiple blocks of code while a menu option is up.

However, for cases where the menu parameter "Set Menu Dialog" is blank, there doesn't appear to be a way to call the .IsActive() function.

I created a work around by going into Menu.cs and changing
 var menuDialog = MenuDialog.GetMenuDialog();
to
menuDialog = MenuDialog.GetMenuDialog();
and adding this line:
public MenuDialog menuDialog;

I could then take a list of all menus in a flowchart, loop through them, and check if they are active.

**Comment by chrisgregan** [comment]
Could you do the same thing just by calling MenuDialog.GetMenuDialog() yourself, rather than storing it the Menu class? I think that should work because only one instance of the menu dialog can be active at a time.

**Comment by chrisgregan** [comment]
Closing this as the MenuDialog.GetMenuDialog() method should be sufficient to solve it.
