### ISSUE TITLE
Proposal: text syntax for flowcharts

### ISSUE THREAD

**Issue by yvan-sraka** [snozbot/fungus#610]
Hello everybody,

I used the Fungus Unity asset during some Game Jam, and I want to thank you first, it's a pretty awesome tool!

But in use, I think it's hard to put a lot of textual content into a game using Fungus, because the cost of using the FlowChart view when writing dialogs is quite expensive.
I would say that the scene mode is pretty good, but if you want to offer many multiple-choice menus to interact with the player it does not seem to be appropriate, or did I miss something?

What I suggest is to offer something like a syntax equivalent to the FlowChart view, to let developers like me the ability to design a game that would follow gameplay patterns faster using text format!
Here is an excerpt from my [MyProjectExample.unity](https://github.com/snozbot/fungus/files/966785/MyProjectExample.unity.txt), I see that the FlowChart states are managed as `MonoBehaviour`, but it is obviously not reasonable to directly edit my `.unity` project file!
A good intermediate syntax could be a compromise between this and the FlowChart view, a sort of low-level syntax that is still understandable by a user, practical as a format for exporting large amounts of content.

Thank you very much for your feedback and advice,

**Comment by chrisgregan** [comment]
Hi Yvan. Have you seen the Lua integration in Fungus? It might do what you're looking for already.
http://fungusdocs.snozbot.com/fungus_lua.html

**Comment by yvan-sraka** [comment]
Yes, that sounds good, thank you very much for your support!
