### ISSUE TITLE
Camera->MoveToView and Camera->FadeScreen interference

### ISSUE THREAD

**Issue by iBicha** [snozbot/fungus#612]
To reproduce:
1-add new flowchart
2-add command Fade screen (duration 1, alpha 1 wait until finished **unchecked**)
3-add command move to view (set a view, assign, etc)

expected behavior:
camera will fade and move to screen simultaneously

actual behavior:
only move to view will be executed.

Remarks:
-just to make sure disable move to view. Fade screen will be working again.

-after inspection, it is due to `StopAllCoroutines` in `CameraManager.cs` line `428`.
One possible fix is, not to stop all coroutines, only stop the ones that are specific to Panning, not fading
Another fix is to separate these functionalities, so they don't interfere
Finally, another possible fix is to redesign the lerp in a way to allow for mixing.

Something like this:
* remove `StopAllCoroutines` in `CameraManager.cs` line `428`.
* change PanInternal function in a way to add only the delta changes, instead of overriding all values:

          ```
      if (camera != null)
                {
					float deltaOrthographicSize = Mathf.Lerp (startSize, endSize, Mathf.SmoothStep (0f, 1f, t)) - camera.orthographicSize;
					Vector3 deltaPosition = Vector3.Lerp (startPos, endPos, Mathf.SmoothStep (0f, 1f, t)) - camera.transform.position;
					Quaternion deltaRotation = Quaternion.Inverse(camera.transform.rotation) * Quaternion.Lerp(startRot, endRot, Mathf.SmoothStep(0f, 1f, t));
					camera.orthographicSize += deltaOrthographicSize;
					camera.transform.position += deltaPosition;
					camera.transform.rotation *= deltaRotation;

                    SetCameraZ(camera);
                }
```
did not make a pull request yet, just to check if this would break anything elsewhere, as im new to the fungus project.

**Comment by chrisgregan** [comment]
Hi iBicha, sorry for slow reply on this. It helps to add the bug label to bug reports so I can spot them easier.

This is some of the oldest (and tbh worst!) code in Fungus so any improvements would be appreciated. Your suggestions are all good approaches. You might also consider using the built in Lean Tween library to perform the tween. 

Keep in mind an important constraint. It's really important to keep the default move behaviour and the properties for the Move To View and Fade To View commands consistent with the existing system. Basically, you can make improvements but it should still be very easy for someone to upgrade an existing project without breaking anything and for someone following an old tutorial video to use the new system without confusion.
