### ISSUE TITLE
Plans to make tween engine swappable or, more specifically, replace iTween?

### ISSUE THREAD

**Issue by snarlynarwhal** [snozbot/fungus#616]
Any desire to swap out iTween for either DOTween or LeanTween in the near future? I heard from various sources that iTween has terrible performance (didn't actually benchmark them myself):

- [iTween iPhone Performance](http://answers.unity3d.com/questions/26073/itween-iphone-performance.html)
- [iTween, DOTween, or LeanTween](https://www.reddit.com/r/Unity3D/comments/2wxazw/itween_dotween_or_leantween/)
- [LeanTween Speed Comparison to iTween](http://dentedpixel.com/developer-diary/leantween-speed-comparison-to-itween/)
- [DOTween - compares near bottom](http://dotween.demigiant.com/)

Has anyone reported fungus not running well on mobile because of this?  I've heard tons of good things about these two. I have been using DOTween and enjoy it very much so far.

**Comment by StefanoCecere** [comment]
yes i was in this topic time ago..
DOTween is great but maybe too complex.. LeanTween is just a script!

**Comment by snarlynarwhal** [comment]
What do you mean by DOTween is too complex? And that LeanTween is just a script?

**Comment by chrisgregan** [comment]
We actually use LeanTween internally in Fungus for stuff like moving portraits on the stage.

iTween is basically terrible, but it's what people were using when I started Fungus. There's now a lot of tutorials and videos out there explaining how to use it, so I don't plan to remove the functionality from Fungus. If somebody wants to contribute new commands that wrap LeanTween I'd be happy to accept a pull request.

**Comment by StefanoCecere** [comment]
@snarlynarwhal i mean: DOTween (that i use everywhere!) is so much powerful, but it creates lots of files to be well setup.. LeanTween is just one file, already embedded in the Fungus core (as @chrisgregan just reminded) so i think it's preferable

**Comment by snarlynarwhal** [comment]
@chrisgregan okay I should have time to do that. I

**Comment by snarlynarwhal** [comment]
Okay, duh, so when I have time, I can create LeanTween commands that mimic the iTween commands. Fungus strictly uses iTween for commands and LeanTween internally, correct? So theoretically, using these LeanTween commands instead of iTween ones should remove traces of iTween usage?

**Comment by konistehrad** [comment]
@snarlynarwhal this was high on my priority list before I got caught up with other work; happy to see someone is taking charge! Looking forward to the PR! :)

**Comment by snarlynarwhal** [comment]
It might be a good couple of weeks before I get to this, but it shall get done! To clarify though:

Fungus strictly uses iTween for commands and LeanTween internally, correct? So using these LeanTween commands instead of iTween ones should remove traces of iTween usage within my project?

**Comment by konistehrad** [comment]
@snarlynarwhal looking at the references, I see references in `CameraManager.cs` and `Writer.cs`; otherwise it's all references to `Command`'s. You're also, for backwards compatibility reasons, going to have to retain the int values from `iTween.LoopType` and `iTween.EaseType` and transform them into something consumable by LeanTween, I think it's `LeanTweenType`.

**Comment by stevehalliwell** [comment]
If this is still desired, I'd propose deprecating all of the old iTween commands entirely rather than trying to match their interface. After a little look into I found that while LeanTween has a 'shake', it is not like iTweens at all. Also means anyone's project that relies on the particular oddness of iTween will not be impacted.

**Comment by chrisgregan** [comment]
A new set of tweening commands based on Lean Tween might be the best approach, don't worry about matching the old iTween interface. I wouldn't recommend removing or deprecating the existing iTween commands as they work fine for many people and there really is a lot of tutorial material out there based on them. Maybe we could show a small warning in the inspector recommending you to use the new Lean Tween based commands instead?

**Comment by stevehalliwell** [comment]
Sounds good, I'll follow that up probably this weekend.

**Comment by konistehrad** [comment]
Upgraded to 2017.2.0f3 today, and unfortunately iTween is looking longer in the tooth than ever. We're getting a mess of warnings out of it:

`Assets/Fungus/Thirdparty/iTween/iTween.cs(4139,26): warning CS0618: `UnityEngine.GUIText' is obsolete: `This component is part of the legacy UI system and will be removed in a future release.'`

When the old Unity GUI types are culled, it looks like the bundled version of iTween will kick the bucket. We should probably decide how we want to deal, either by excising the old GUI references, or performing a more aggressive migration (removal of iTween commands in favor of @stevehalliwell's PR?)
