### ISSUE TITLE
sound when bouncing with Fungus / Unity

### ISSUE THREAD

**Issue by REPORTERTV** [snozbot/fungus#621]
Hi,
how do I make a rigidbody object with the bouncy material set on its collider play a noise every time it bounces with Fungus / Unity?
Thanks

**Comment by stevehalliwell** [comment]
If you can download and check my fork and branch https://github.com/stevehalliwell/fungus/tree/physics_events there's a physics interaction example scene in there. If that meets requirements then I'll clean it up and submit as a pull request.

**Comment by stevehalliwell** [comment]
This functionality is now in Fungus 3.7
