### ISSUE TITLE
More EventsHandlers?

### ISSUE THREAD

**Issue by stevehalliwell** [snozbot/fungus#623]
Definitely a feature request / enhancement but...

Along the lines of #621 and the [Hover question](http://fungusgames.com/forum#!/fungus-development:mouse-hover-on-a-sprite) from the forum.

What about having Fungus EventHandlers for as many of the [Unity MonoBehaviour Messages](https://docs.unity3d.com/ScriptReference/MonoBehaviour.html) as possible?

I get students, who have taken to Fungus, asking "Can I use Fungus to do X?" and often that answer is yes, but you'll need to write c# to call the fungus block when the right circumstances are met or write a new EventHandler.

**Comment by chrisgregan** [comment]
Hey Steve, take a look at the ExecuteHandler script in FungusLua. It allows you to execute a Lua script based on any of the standard Unity events. I based it on the Assertion component in the Unity Test Tools. It wouldn't be hard to adapt it to make a Fungus event handler that does what you're talking about.

**Comment by stevehalliwell** [comment]
Cool, thanks for the heads up. I had a look and what I had started messing around with was similar. Right now I'm trying out the idea of there being a bunch of them that handle all the related Unity Messages. E.g. a Trigger EventHandler receives OnTriggerEnter, OnTriggerStay and OnTriggerExit, you state which of those you are interested in and can also compare the collider's tag to a collection.

I'll need to do up a bunch of Example Scenes too.

**Comment by chrisgregan** [comment]
Sounds great!
