### ISSUE TITLE
Playground Project

### ISSUE THREAD

**Issue by stevehalliwell** [snozbot/fungus#632]
I'm working on commands, events, and demo scenes to match the functionality found here https://github.com/UnityTechnologies/PlaygroundProject

Keen for others thoughts on structure and desired features.

For example it has required some interaction with the Rigidbody2D from Fungus, so far only Force and Torque. Would it be preferred that there are only commands for things being used or would it be preferred that "Well if we're going to talk to the rigidbody2d, we should also be able to change it's drag, mass,etc."

**Comment by chrisgregan** [comment]
Sounds cool. If there were RigidBody2D commands in Fungus I guess I'd expect to be able to set any RigidBody properties using it, rather than just a subset that was used in a particular example.
