### ISSUE TITLE
Flowchart references are never released on Unity 5.4+, leading to big memory leaks

### ISSUE THREAD

**Issue by zvinless** [snozbot/fungus#638]
Once a flowchart loads, it and its dependencies stay in memory forever on Unity 5.4+. It's being caused by a couple of things: 

Event Handlers that handle static events and are never removed:
- [Flowchart.cs Line 94](https://github.com/snozbot/fungus/blob/master/Assets/Fungus/Scripts/Components/Flowchart.cs#L94)
- [Localization.cs Line 47](https://github.com/snozbot/fungus/blob/master/Assets/Fungus/Scripts/Components/Localization.cs#L47)

static references in UI objects that hold references to lots of other things (these probably need to get nulled out when leaving the scene):
- `SayDialog::ActiveSayDialog`
- `SayDialog::speakingCharacter` (for character resources specifically)
- `MenuDialog::ActiveMenuDialog`

It can get pretty bad because flowcharts end up referencing character sprites and music through their commands.

**Comment by stevehalliwell** [comment]
Thanks for the report. The flowchart and localization SceneManager delegates definitely look like they need to be unregistered, given that they are hooked to a UnityAction rather than a UnityEvent.

I'm going to leave the other statics you've mentioned for Chris to look at in the future.
