### ISSUE TITLE
iTween.cs warnings on compilation

### ISSUE THREAD

**Issue by mvriel** [snozbot/fungus#644]
In Unity 2017.2 beta I get a series of the following warnings:

```
Assets/Fungus/Thirdparty/iTween/iTween.cs(708,26): warning CS0618: `UnityEngine.GUITexture' is obsolete: `This component is part of the legacy UI system and will be removed in a future release.'
```

Since these are warnings they do not (yet) break anything but I'm trying to keep a clean build and wonder if it is possible to resolve these?

**Comment by chrisgregan** [comment]
Thanks for the report, I've removed the obsolete code that was causing the warnings.

**Comment by mvriel** [comment]
I have installed the latest update of Fungus and this is no longer causing warnings; thank you so much for tackling this

**Comment by chrisgregan** [comment]
You're welcome!
