### ISSUE TITLE
Indicating ontop of blocks in flowchart editor where they are called from

### ISSUE THREAD

**Issue by Tom-III** [snozbot/fungus#653]
It would be a valuable debugging tool if the blocks in the flowchart view would indicate somehow where they are called from like "Callers: FlowchartName>BlockName" so its easy to trace back who called this script on large and complicated scenes.
By call I mean the "Call" command from the Flow category, not call from C# scripts as this would be very difficult to detect.
Sometimes in large scenes you can waste quite a bit of time trying to find out who called this block

**Comment by stevehalliwell** [comment]
Are you imagining something that shows an equivalent of something like a Fungus Call Stack at run-time in the editor somewhere?

**Comment by Tom-III** [comment]
Something like what find usages does in visual studio
