### ISSUE TITLE
No flowchart window in Unity 2017

### ISSUE THREAD

**Issue by AslamPangestu** [snozbot/fungus#660]
I can't activate flowchart window in unity 2017.03. Can you help me?
![screenshot 21](https://user-images.githubusercontent.com/26374086/36584977-8506d336-18ae-11e8-8bf4-7376c08c0d09.png)

**Comment by stevehalliwell** [comment]
That looks like, non latest version of Fungus opened in newer Unity or perhaps not allowing Unity to run the auto upgrade when Fungus was imported. If you import Fungus again does it offer the auto upgrade?

**Comment by AslamPangestu** [comment]
no. there is offer to upgrade. i use the file on github to. but the result is same
