### ISSUE TITLE
Cannot edit Blocks in Unity 2017.3.0f3

### ISSUE THREAD

**Issue by Domiii** [snozbot/fungus#667]
I tried new scenes and existing example scenes; but the result is always the same: I don't get the editing tools in the Inspector when selecting a block.

![image](https://user-images.githubusercontent.com/282899/38187682-49bb1346-368b-11e8-9d01-1f173d39b6f2.png)

It tells me to use the `+` button, but there is no button, and no other editing UI :/

**Comment by Domiii** [comment]
The bug is: the block Inspector does not support scrolling!
The editing tools are below, and only show up when the inspector window height is sufficient

**Comment by stevehalliwell** [comment]
Can you provide any more details about the circumstance? Like OS, Screen Resolution, etc.

**Comment by Domiii** [comment]
I am using Mac OS on a MacBook Pro w/ default resolution - don't think the resolution should have an impact on whether or not the inspector window is scrollable?

I haven't checked your source code (and I admit, this is might not be that big a bug), but are you using/have you considered using [BeginScrollView](https://docs.unity3d.com/ScriptReference/EditorGUILayout.BeginScrollView.html)?
