### ISSUE TITLE
Bug with audio command "Play Music"

### ISSUE THREAD

**Issue by AliAkbarMontazeri** [snozbot/fungus#674]
There are 2 scenes in my game, first is main menu and second is game. I had BGM playing from the block which I set it to run when the game started in my game scene. When I loaded the main menu scene from the game scene, it thought it's automatically stopped the BGM. So I added the "Stop Music" command before I loaded the main menu scene. And it works just as I expected, but when I loaded the game scene again the BGM wasn't playing (it should play because I had a block contains "Play Music" command which runs when the game started). How do I resolve this ? Thanks

**Comment by stevehalliwell** [comment]
There was a bug fix for a bug related to stopping and playing music in Fungus 3.8 is this separate from that issue?
