### ISSUE TITLE
Fungus Error please help

### ISSUE THREAD

**Issue by rossk3lly** [snozbot/fungus#680]
Hi, 
I've re installed Unity to the latest version and when creating a brand new project the following error is present even though I haven't even starting creating anything:

![screen shot 2018-05-03 at 15 27 44](https://user-images.githubusercontent.com/24506379/39588097-fafbc0e0-4ef2-11e8-844e-584a0555e2e5.png)

Also I selected the Fungus assets when setting up the project name etc.. but there is no toolbar to access the fungus options within the project.

Can anyone help?
Thanks

**Comment by stevehalliwell** [comment]
Was also raised here http://fungusgames.com/forum#!/support-questions:unity-201810f2-and-fungus should just be that simple fix in that script file.
