### ISSUE TITLE
URGENT! Final College project Due and 1000+ errors 

### ISSUE THREAD

**Issue by shanepdc** [snozbot/fungus#684]
Hi,

My final year project is due in 4 days and I went to build and have been given 1000+ errors.

Here are some of the errors.  Can anyone please help

Assertion failed: Assertion failed on expression: 'success && actual == (UInt64)size' UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)      < this error seems to be repeated 100's of times

<img width="721" alt="screen shot 2018-05-09 at 21 41 15" src="https://user-images.githubusercontent.com/24306929/39838603-c5a7b410-53d1-11e8-8a2f-0cd78018852b.png">

Above is a different error which I can see down the end of the error list/

Please if anyone can help. Thank you!

**Comment by StefanoCecere** [comment]
i guess you solved this, right?
i would reinstall Unity to fix it
