### ISSUE TITLE
Sample Playground project "Football" Input issue.

### ISSUE THREAD

**Issue by paulmcgrath** [snozbot/fungus#687]
The Player controller in the Playground > Football.scene has an error

![screen shot 2018-05-18 at 16 44 13 2](https://user-images.githubusercontent.com/5718275/40244567-1709e540-5abb-11e8-9e6a-956356476445.png)

**Comment by stevehalliwell** [comment]
Caused by the unitypackage not including the input axes that exist in the source fungus project. 
#683 adds GetKey commands and updates Football to use those instead of GetAxis

**Comment by paulmcgrath** [comment]
Hi Steve, Im still trying to get the Football example to work! Ive reinstalled Fungus a few times but it still gives me the same error (see below) has the GetKey command been added to the latest release 3.8?



ArgumentException: Input Axis p1xAxis is not setup.
 To change the input settings use: Edit -> Project Settings -> Input
Fungus.GetAxis.OnEnter () (at Assets/Fungus/Scripts/Commands/Input/GetAxis.cs:35)
Fungus.Command.Execute () (at Assets/Fungus/Scripts/Components/Command.cs:113)
Fungus.Block+<Execute>c__Iterator0.MoveNext () (at Assets/Fungus/Scripts/Components/Block.cs:282)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Fungus.Flowchart:ExecuteBlock(Block, Int32, Action) (at Assets/Fungus/Scripts/Components/Flowchart.cs:575)
Fungus.EventHandler:ExecuteBlock() (at Assets/Fungus/Scripts/Components/EventHandler.cs:74)
Fungus.UpdateTick:FixedUpdate() (at Assets/Fungus/Scripts/EventHandlers/MonoBehaviour/UpdateTick.cs:42)

**Comment by chrisgregan** [comment]
Hoping to release 3.9 this week.

**Comment by paulmcgrath** [comment]
Thanks Steve & Chris, looking forward to the new release. On a separate note I havent forgotten the videos, I just haven't found the time yet. BUT i  will promise

**Comment by paulmcgrath** [comment]
Whoo Hooo its all working, thanks
