### ISSUE TITLE
Update bundled LeanTween version

### ISSUE THREAD

**Issue by stevehalliwell** [snozbot/fungus#688]
as discussed on [forum here](http://fungusgames.com/forum#!/support-questions:really-odd-portrait-fading) 
The alternate is we hide leantween 2.3 inside the fungus namespace, so they don't conflict or interact. I'd prefer that if users know they have the latest leantween already there are working if they have the latest fungus

**Comment by StefanoCecere** [comment]
in OpenSource projects it's not best practice to embed external libs under own namespace.
much better to leave them as they are (maybe with a public dependencies doc)

it wouldn't harm casual developers using just fungus
and anybody having already a LeanTween lib in their project can easily solve the conflict by using the most recent version

so i suggest to take LeanTween out of the Fungus namespace!
