### ISSUE TITLE
Unity 2018.2.0f2 BooleanData variables show internal name in the inspector

### ISSUE THREAD

**Issue by marchys** [snozbot/fungus#700]
It seems that in the new version of unity the inspector values of BooleanVariable are wrong (they show the internal name instead)
![imatge](https://user-images.githubusercontent.com/10723954/43222659-0a12b6a2-9051-11e8-9add-03a1194250f8.png)

If I have some time tomorrow I'll look into it

**Comment by marchys** [comment]
It seems that adding the name to the prop fixes the problem but you have to do that for each one of them. 
```C#
EditorGUILayout.PropertyField(hideThisOptionProp, 
new GUIContent(hideThisOptionProp.name, hideThisOptionProp.tooltip));
```
Anyone knows a better solution to this?

**Comment by stevehalliwell** [comment]
Culprit appears to be EditorGUI.GetPropertyHeight(valueProp, label) in the VariableEditor line ~212, it seems to modify the label it is given. Submitting bug fix now.
