### ISSUE TITLE
Save Point starting in the wrong view

### ISSUE THREAD

**Issue by TheColorRed** [snozbot/fungus#713]
I am using the save system, I have `Load On Start` and `Auto Save` enabled. Throughout the game there are multiple save points within one `View`, and when I press stop in the editor and play again, it picks up from where it left off, but it is showing the first view instead of the one that it is viewing at the current save point.

Is there something else that needs to be done? Do I need to load the view after the save point again?

**Comment by chrisgregan** [comment]
Do you maybe have a Block with Execute On Event set to Game Started? If you're using the save system then you should only use Scene > Save Point Loaded which handles both normal scene start and starting after a load.

**Comment by TheColorRed** [comment]
I do have one with game started, but it doesn't do anything other than make an http request to a remote server to get the `PlayerPrefs`. Is there a better way to load `PlayerPrefs` from a remote server?
