### ISSUE TITLE
Cloned repo, two tests failed

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#714]
I wanted to add a feature that gives the user the option to have the Say Command wrap the text to multiple dialog boxes. As per the Contributions guide, I cloned the repo and ran all the tests before adding anything. Two of the tests failed. 

Here is a screenshot: https://imgur.com/a/QHV115u

**Comment by stevehalliwell** [comment]
Can you provide some more detail on your build and version. I can get the Stop test to fail in build, but not editor but I cannot get the string sub test to fail at all.

In terms of adding and doing a PR I say put one through as long as it isn't causing any new failures.
