### ISSUE TITLE
cannot select blocks

### ISSUE THREAD

**Issue by callmearcturus** [snozbot/fungus#715]
I'm unsure anyone will be able to assist with this. I am incredibly new to Unity, having picked it to work on my next game with after Ren'py. Fungus seemed the best way to ease into the engine and learn what I'm doing. Unfortunately, a very bedrock basic function is not working: I cannot click on and select any blocks in the flowchart. They will not show up in the inspector window. I cannot examine the blocks in the sample games that come with Fungus, nor can I do any with my own blocks in any new projects.

![gdi unity](https://user-images.githubusercontent.com/44908407/48285745-8d4d8b80-e431-11e8-8324-80fa1a641d10.gif)

It is my greatest dream that this is some newbie user error, but I have no idea how to fix it. I have already updated Unity to its latest version, then updated Fungus to the latest version, then created brand new projects. Through it all, the issue remains.

Guidance would be greatly appreciated.

**Comment by chrisgregan** [comment]
Hey - can you double check that you're on the latest version of Unity? 2018.2.14f1

The update dialog in Unity is broken and will say you have the latest version when you don't :)

**Comment by TheColorRed** [comment]
Do you have an update event block? I have one, and you cant select anything if there is an update event block, and you need to disable it. I think that that is a bug either way...
