### ISSUE TITLE
Unity 2018.3 Warnings 

### ISSUE THREAD

**Issue by Lawendt** [snozbot/fungus#723]
In the new unity 2018.3 the prefab workflow has changed and there are warnings being thrown.
![image](https://user-images.githubusercontent.com/13232242/50151293-a571bf80-02a7-11e9-883d-dd74a612d382.png)

**Comment by konistehrad** [comment]
I think this fix might have blown up pre-2018.3 compatibility, unfortunately. `PrefabUtility.UnpackPrefabInstance` is only available in 2018.3+. Recommend the following:

```C#

#if UNITY_2018_3_OR_NEWER
            PrefabUtility.UnpackPrefabInstance(go, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
#else
            PrefabUtility.DisconnectPrefabInstance(go);
#endif

```
