### ISSUE TITLE
unity 2019 issue

### ISSUE THREAD

**Issue by BaLaLaLs** [snozbot/fungus#724]
Version 2019.1.0a11 (0f106840e011) Personal
BlockInspector.cs line 215  
` EditorGUIUtility.AddCursorRect(cursorChangeRect, MouseCursor.ResizeVertical);` in unity 2019 throw error chnage to 
` EditorGUIUtility.AddCursorRect(cursorChangeRect, UnityEditor.MouseCursor.ResizeVertical);` fix
and create a block then click , inspector not show anything
![image](https://user-images.githubusercontent.com/23353559/50261520-db4daa00-0447-11e9-8df4-19e2bb35d3ad.png)

**Comment by stevehalliwell** [comment]
Do you know what version of Fungus you are using? 
Also are you on Windows, Mac or Linux?

**Comment by stevehalliwell** [comment]
Some initial digging indicates that the previous trick in BlockInspectors UpdateWindowHeight does not work in 2019.1a. Also it seems use of GUILayout.BeginArea is not playing nice.

**Comment by Kewry** [comment]
Having what appears to be this on 2019.1.0a13, windows 7.
It's my first time running Fungus and all examples show empty inspector when clicking a block

**Comment by dobryc** [comment]
Still getting this issue. Latest Fungus from Asset store, Unity 2019.1.5f1
