### ISSUE TITLE
Custom Commands Don't Appear with Fungus Root in /Assets/Plugins

### ISSUE THREAD

**Issue by digiwombat** [snozbot/fungus#734]
_**Amended per conclusions from below**_

Fungus does not find custom commands when placed in the /Assets/Plugins Special Folder (otherwise seems to work in any other random folder)

Examples:

Imported to: Assets/Fungus 
-> All Commands Found

Moved to: Assets/Plugins/Fungus
Command in:
Assets/Plugins -> FOUND
Assets/Plugins/Commands  -> FOUND
Assets/Commands -> NOT FOUND
Assets/Scripts/Commands -> NOT FOUND

If this can't be worked around, that's fine, but I feel like it should be documented in some way or that custom commands should be more clearly given a standard folder to reside in.

Obviously, the ideal here is that we can use whatever folder structure we want and we can move Fungus around to whatever our hierarchy style guide needs it to be.

Either way, minor issue, but hopefully it'll help anyone who ends up confused for two days like me.

**Comment by chrisgregan** [comment]
I think this is happening because 'Plugins' is a special folder name in Unity, with specific behaviour.
https://docs.unity3d.com/Manual/SpecialFolders.html

If you use a folder with a different name it should work ok.

**Comment by digiwombat** [comment]
Confirmed that that's the case (at least with two randomly named folders).

I'll amend the bug. Since it seems rare enough that people move it to that folder, a note in the documentation might be enough to call it dealt with.

**Comment by stevehalliwell** [comment]
This is also related to issues around asmdef use, reported on the form, [link](http://fungusgames.com/forum#!/support-questions:how-do-you-use-custom-comma)
