### ISSUE TITLE
About the "breaking changes" the save system may have

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#748]
Does this mean that pull requests for changing the save system won't have to worry about the backwards-compatibility rule? If not, then how much more freedom than normal (if any) are contributors allowed? The page on fungusdocs.snozbot.com did say the system's still in beta.

**Comment by stevehalliwell** [comment]
I'd lean towards don't break, unless you must. I'd also tend to be most concerned with people that are in development of an unreleased project, so internal and public API changes wouldn't be a huge issue but removal of existing functionality would.

What kind of changes are you considering?

**Comment by CG-Tespy** [comment]
The kinds of changes I was considering have been implemented here:
https://github.com/CG-Tespy/Fungus-Slot-based-Save-System (mostly this one)
https://github.com/CG-Tespy/Fungus-Slot-based-Narrative-System

Among other things, they are:
- Decoupling the Save and Narrative Log Systems
- Making the Save system slot-based
- Using the JSONUtility class (first introduced in Unity 2017)

I minimized changing the built-in Fungus API with the first two (I put my custom code into separate namespaces), but that last one poses a problem. This repo's documentation says any changes have to work with Unity 5.0, but my implementation uses the JSONUtility class, which was first introduced in Unity 2017. 

Plus, if my implementation were to be accepted in an official release, then much of the old save system's code would need to be thrown away; it's redundant. And that would break systems that were replying on it before.

**Comment by stevehalliwell** [comment]
I think the contribution guidelines need an update, 2017/2018+ makes sense.

I don't think there's anything wrong with replacing or updating the existing save system. If your new system is a whole replacement of the previous and can fit within the existing EventHandlers & Commands that interact with the save system then the impact to users would be near zero.

**Comment by CG-Tespy** [comment]
I agree, it could use an update. And by "existing EventHandlers and Commands", do you mean Save Variable, Load Variable, Set Save Profile, and Delete Save Key? If I remember right, the current official system rendered those obsolete. And my system simply doesn't use those, since it already handles what those commands do.
