### ISSUE TITLE
If statement should allow multiple conditions

### ISSUE THREAD

**Issue by AcademyOfF** [snozbot/fungus#778]
I often wish I could have an IF command that says `if x and y` or `if x or y`.  I'd want multiple conditions, e.g., the ability to say, `if a and b and c and d...`

I'd be happy to try to implement this myself, the only problem is I don't know how to make it backward compatible so the existing if statements still function as they did.

**Comment by stevehalliwell** [comment]
If you're having to alter the underlying data being stored in the command(s), you can leave the existing data there, but put HideInInspector on it. Then implement [ISerializationCallback ](https://docs.unity3d.com/ScriptReference/ISerializationCallbackReceiver.html)and in the OnAfterDeserialize method convert the existing data into the format of the new data.

Also feel free to start a PR even if it's incomplete for ongoing feedback and assistance.

**Comment by AcademyOfF** [comment]
I was unable to figure out how to do this, so I'm taking a different route.  I'm creating a Boolean Algebra command.  If you'd be interested in it, let me know and I can share it.  Either way, I'd still prefer if's with multiple conditions.

**Comment by AcademyOfF** [comment]
Here's what I came up with.  I don't like it very much, but it gets the job done.  Maybe i'll give you ideas, but I doubt you'll want it directly. 

https://pastebin.com/C9zh0Kxr
https://pastebin.com/p9RMxaE3

**Comment by stevehalliwell** [comment]
Thanks for sharing the snippets. They'll be useful along side the conditions, variables, and looping improvements I was looking into.

**Comment by preda2or** [comment]
I would like to work on the issue. Any specific design i should keep in mind during its implementation?

**Comment by stevehalliwell** [comment]
Make sure you start from dev branch, there are some changes to the internals of the control flow commands and in particular the conditional command.

The imagine the UI is going to be a mess, I think we should work through that in an early PR.

Feel free to shout in here or in an incomplete PR for help and feedback.

**Comment by preda2or** [comment]
For this issue, do we need brackets
eg., 

**(exp1 or exp2) and exp3**

Or simply, we just need all expressions combined with "and, or, not" ?

And in the UI, I am planning to do the simple version inside the If expression block using multiple expression blocks joined by "or, not, and" dropdowns

**Comment by AcademyOfF** [comment]
Ideally, parentheses will be allowed. Otherwise, you'd have to pick which associativity you want. When you're really programming, you don't think this way. If there is doubt about which part of this statement is going to be executed first, you wrap it in parens.

I'll admit, I can't visualize how this will work. Maybe can be done with indentation? The parts that are indented the furthest to the right are executed first?

Honestly, I think the first step in this feature is visualizing it, not implementing it.

**Comment by preda2or** [comment]
I propose 2 options in my solution:

For complex expressions(with brackets), what i suggest is that we simply let the developer enter the expression as string (with brackets), which can then be converted to c# expressions and can then be evaluated according to the conventional rules of logical expressions (precedence - NOT>AND>OR). I feel that this will be much simpler and more intuitive for any developer than any UI we come up with. I suggest doing this in a new command and the result can be stored in a new boolean variable which can be used in if conditions.

For simple use cases(without brackets), we allow multiple logical expressions joined by AND, OR logical operators directly in if command itself.

**Comment by AcademyOfF** [comment]
I thought of this too I don't like this solution because it opens itself up to so many possible human errors. If you're typing by hand, you can have a typo. I'm going to get variable names wrong all the time. It is also inconvenient to type out the full names. There won't be any auto complete in this text field.

The typo aspect would be greatly minimized if the command could check for any syntax errors, and that doesn't seem too difficult to me to implement. But I don't know how you would deal with the inconvenient aspect. Perhaps that's just something that needs to be compromised on.

On the other hand, I think there might be a lot of SQL tools that can generate queries through UIs. Maybe they would be a good example of what to look at if you want to build an if statement because they'll be similar to a SQL where clause.

**Comment by stevehalliwell** [comment]
Two types of 'If' feels a bit off to me. Resolving this with a more robust 'If' and a second more complex boolean algebra style command like AcademyOfF had originally, is a good solution. So for now, I'd recommend focus on what the minimum of a robust 'if' looks like.

We may be covering the majority of frequent cases by simply having a list of the conditions and a tick box for All of these/Any of these. Also a user that wants a very specific and 'complex' conditional, may be wanting to use LuaIf anyway.

Note that the improved VariableCondition shouldn't become any harder to use or require more clicks than it does presently.

I'm excited by the idea of having the user enter pseudo logic and having the command editor check and determine the underlying data it would actually store, but I would keep that as a Phase II of this issue. Goal here should be allowing things like 
- If hasRedKey == true AND wasRudeToMargret == false
- if passwordCorrect == true OR charisma >= 80
