### ISSUE TITLE
v3.12.0-rc1 errors in Unity 2018

### ISSUE THREAD

**Issue by testerda** [snozbot/fungus#783]
Tested on 2018.4.13 and 2018.4.14, getting same errors when imported into empty projects.

![Clipboard01](https://user-images.githubusercontent.com/48183861/70762863-3030b180-1d78-11ea-95b8-ad0fa38da2da.png)

**Comment by stevehalliwell** [comment]
Thanks for the report. Did you encounter that with regular, Lite, or 2017 unitypackage? Or all of them?

**Comment by testerda** [comment]
> 
> 
> Thanks for the report. Did you encounter that with regular, Lite, or 2017 unitypackage? Or all of them?

I only used the regular package.

**Comment by stevehalliwell** [comment]
If you are able to, could you try the 2017 unitypackage?

**Comment by testerda** [comment]
> 
> 
> If you are able to, could you try the 2017 unitypackage?

Heh, I missed 2017 somehow before. But just tested it, works fine on both Unity 2018 versions above.

**Comment by stevehalliwell** [comment]
The 2017 compat version has the same changes and changelog right now. We use the UNITY_VERSION defines for version specific code. At present there is no functional difference, just the 2017 has no asmdefs and if you are trying to use TMPro, demo scenes that rely on TMPro will throw errors until you manually add TMPro to the project.

Thanks very much for checking and reporting. I'll make the naming and differences for the compat version clearer in the final release.
