### ISSUE TITLE
Cannot add variable to Flowchart or set Execute on Event param

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#803]
**Describe the bug**
When I click the + button for adding a variable (or the control for setting a block's Execute on Event property), nothing pops up to let me use those features. I do, however, get an error logged to the console.

The contents are as follows:
"
NullReferenceException: Object reference not set to an instance of an object
Fungus.EditorUtils.EventSelectorPopupWindowContent.DoOlderMenu (Fungus.Block block) (at Assets/Fungus/Scripts/Editor/PopupContent/EventSelectorPopupWindowContent.cs:96)
Fungus.EditorUtils.EventSelectorPopupWindowContent.DoEventHandlerPopUp (UnityEngine.Rect position, System.String currentHandlerName, Fungus.Block block, System.Int32 width, System.Int32 height) (at Assets/Fungus/Scripts/Editor/PopupContent/EventSelectorPopupWindowContent.cs:82)
Fungus.EditorUtils.BlockEditor.DrawEventHandlerGUI (Fungus.Flowchart flowchart) (at Assets/Fungus/Scripts/Editor/BlockEditor.cs:358)
Fungus.EditorUtils.BlockEditor.DrawBlockGUI (Fungus.Flowchart flowchart) (at Assets/Fungus/Scripts/Editor/BlockEditor.cs:123)
Fungus.EditorUtils.BlockInspectorEditor.OnInspectorGUI () (at Assets/Fungus/Scripts/Editor/BlockInspector.cs:111)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1647)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
"
This bug happens randomly, though when it first happens in a project, it keeps happening until I remove and reinstall Fungus. Even then, it only sometimes solves the issue.

**To Reproduce**
Just keep working on a project in Fungus, and somehow hope the error shows up?

**Expected behavior**
That I'm able to add variables and set what events that blocks can execute in response to.

**Versions & Platform**
 - Unity 2018.4.12f1
 - Fungus version 3.10.0 (latest version I could get to work with Unity 2018 without issues from missing dependencies)
 - Editor OS: Windows 10
 - Build Platform: PC

**Additional context**

**Comment by stevehalliwell** [comment]
The compatibility version available here https://github.com/snozbot/fungus/releases/tag/v3.12.0 should work in 2018.4 I've not tested it against that exact bugfix version though. If that is giving compile errors please let us know.

If more information becomes available please update the 'To Reproduce' section.

**Comment by CG-Tespy** [comment]
Resolved the issue by upgrading as you suggested. Thank you :)
