### ISSUE TITLE
How to know if a menu list is showing?

### ISSUE THREAD

**Issue by creamJelly** [snozbot/fungus#804]
My aim is to know if a menu list is showing on screen.
I tried GetExecutingBlocks() , but when a menu is showing ,it not works.
I want to show a icon while this is no  chart is executing,  also incloud menu.

For example :
In picture A && C, when player walk into trigger range, then show a UI with "press E"
In picture B, when player press e, then show the chart and the UI is hied.

But, in picture D. When player press e, but the UI is still showing, and menu list is also showing.

Thanks

![微信图片_20200311145913](https://user-images.githubusercontent.com/10293381/76390838-1b7cad80-63a9-11ea-88a2-c2655b94fb66.png)
![微信图片_20200311145919](https://user-images.githubusercontent.com/10293381/76390844-1fa8cb00-63a9-11ea-936c-6a2677a224a6.png)
![微信图片_20200311145922](https://user-images.githubusercontent.com/10293381/76390846-20416180-63a9-11ea-982a-3aa69195eb70.png)
![微信图片_20200311145925](https://user-images.githubusercontent.com/10293381/76390847-20d9f800-63a9-11ea-803f-8d0b682668cb.png)

**Comment by stevehalliwell** [comment]
Yes, you are correct in that a block is not executing when a menu is visible. You most likely want to listen to the MenuSignals for starting and ending showing menus.

**Comment by creamJelly** [comment]
I got it.
Thank you very much!
