### ISSUE TITLE
"Wait before next Say dialogue" option

### ISSUE THREAD

**Issue by TheEmbracedOne** [snozbot/fungus#806]
Hi, I'd like to request the addition of a public variable to Say or Writer so that users could configure how long a say command should wait after finishing before showing the next say command.

I have "wait for click" off, and right now if a say dialogue consists of a 1-2 word sentence, it is on the screen for less than a second. Just like I'm able to specify punctuation pause, it'd be great to be able to specify a minimum duration for how long each say dialogue should be displayed for.

There's probably a abetter way to do this, right now I was able to get this to work the following way:

Say.cs script, from line 133
```
sayDialog.Say(subbedText, !extendPrevious, waitForClick, fadeWhenDone, stopVoiceover, waitForVO, voiceOverClip, delegate {
                StartCoroutine(ExampleCoroutine());
            });
        }

        IEnumerator ExampleCoroutine()
        {
            yield return new WaitForSeconds(waitForDuration);
            Continue();
        }
```

Hope you'll consider adding this!

**Comment by TheEmbracedOne** [comment]
PS. the problem with my implementation is that while I got the say editor to display this field and I can give it a value, I'd like to have this as a global value, ie on the Writer script or someplace similar, so I wouldnt have to set it for every single say dialogue.

**Comment by TheEmbracedOne** [comment]
apparently what I wrote above does not work as intended and to clarify, the intent here would be to make sure a piece of text stays on the screen for a desired X secs before the next Say command triggers.

**Comment by stevehalliwell** [comment]
Writers currently support a wait token which will hold for a given number of seconds. Such as {w=1.5}. It seems to be intended for author to configure dramatic delays as required. Given you want a global one, I would recommend adding some code to your writer or say that appends a string with your desired wait time to everything it is asked to process. This is similar to how wait for input is handled presently.

**Comment by TheEmbracedOne** [comment]
Hi @stevehalliwell and thanks for the reply. I think I know which wait token you mean (punctuation pause?), but what I'd like to do is ensure that each Say command stays on screen after finishing writing for X duration. I tried adding a Coroutine as per my above example, but unfortunately I cannot figure out where in Say.cs or Writer.cs I should add this, or any other code, because I'm not a programmer. Could you advise me on this please? I'd greatly appreciate it.

**Comment by CG-Tespy** [comment]
Would something that effectively adds a {w=insertUserDesignatedNumberHere} at the end of every Say command's story text be good enough, or...?

**Comment by TheEmbracedOne** [comment]
@CG-Tespy that's essentially a Wait command right? As long as it makes the next say command "wait" without having to add a Wait command every single time, I dont see a problem with it. 

Something I didnt mention above, ideally this would work smoothly with voiceover - I'd imagine the wait would need to be triggered after the check for whether the voiceover has finished playing has happened.

**Comment by CG-Tespy** [comment]
@TheEmbracedOne Yes, it is. Also, I've engineered a solution, albeit one that doesn't take voice clips into account. First, overwrite the contents of your Say.cs file with what you see here: https://github.com/CG-Tespy/fungus/blob/SayDelay/Assets/Fungus/Scripts/Commands/Say.cs

Then create a new script called SetSayEndDelay.cs, with the contents you see here: https://github.com/CG-Tespy/fungus/blob/SayDelay/Assets/Fungus/Scripts/Commands/SetSayEndDelay.cs

With this, you have a command that lets you set a global delay applied to all Say commands. It can be either a variable or a hard-coded value. I hope this helps

**Comment by TheEmbracedOne** [comment]
@CG-Tespy thank you!! When you say it doesnt take into account voice clips - does this mean if I have voice clips (with wait for VO ticked on), it wouldnt work properly, or does it mean it waits at the end regardless of a voice clip?

If the former, how can I make it so that the wait starts at the end of a voice clip finishing?

The idea is to have a bit of a delay at the end of each line, even if they have voiceover, so that it doesnt start the next one right away, giving the player some more time to read.

**Comment by CG-Tespy** [comment]
You're welcome ^_^ Also, it means that it waits at the end regardless of a voice clip.

**Comment by TheEmbracedOne** [comment]
Fantastic!! Thank you so much!

I tried this now and it's great, but I realised that without my previous hacky "fix", the current say command now sort of overlap with the next one. I'm attaching a GIF to illustrate the problem:
![8AXQsxTSN2](https://user-images.githubusercontent.com/16197906/93027848-52a17500-f5ff-11ea-81ae-3cd0fe28b180.gif)

Fortunately, I know what's causing this problem; I'm using different say dialogs for each character. This is because I have an audiosource on each say dialog that all use a different, character-specific mixer, so I cannot unfortunately use the same say dialog for different characters, until something like #843 or something similar is implemented.

Unfortunately, I dont know what would fix the problem, my guess would be another wait with a different variable for after the "Fade when done" finishes (so when the current text has completely disappeared). 

I feel cheeky for asking you for this since you've already helped me, but would you kindly consider tackling this problem for me?
I'd super appreciate it.

**Comment by CG-Tespy** [comment]
Strange, that issue didn't happen on my end. Can you show me a screencap of the settings your Say commands used? I get the feeling that changing those could fix the issue, without needing any hacky fixes...

Putting aside that my solution is in itself kind of hacky xD

**Comment by TheEmbracedOne** [comment]
Of course, here they are:
![Lqv95oC7v5](https://user-images.githubusercontent.com/16197906/93276555-68559c80-f7af-11ea-81b3-8f194a284add.png)
![wH61tYI7XC](https://user-images.githubusercontent.com/16197906/93276556-68ee3300-f7af-11ea-957e-82c8994e18ff.png)

Any ideas?

**Comment by CG-Tespy** [comment]
Alright, I've tested things on my end with similar settings (voice clip, show always, fade when done, wait for vo) and things still worked fine. Perhaps there's something else going on in your flowcharts causing this issue; on my end, fading only happened when the flowchart got to the last say command

**Comment by TheEmbracedOne** [comment]
Hmm, I think I know why! In the Say Dialog script, there is an option for "Close other dialogs" which did it! Now it works perfectly. Thank you again

**Comment by stevehalliwell** [comment]
I think this would be a good addition to Fungus in general. I think a number of users would benefit from a configurable global wait at the end of every Say. I'd like to see it go in as a PR if you are willing.
