### ISSUE TITLE
Savemenu - Delete Save Data often doesn't delete the save_data.json file

### ISSUE THREAD

**Issue by ianicmathieu** [snozbot/fungus#808]
I've been using the SaveMenu item in my project, and many time the button : Delete Save Data fails to work.

It seem to work a few times, then completely stops working ( perhaps after restarting Unity?

I now always have to delete the file manually.

 - Unity version [e.g. 2019.2.10f1

**Additional context**
I'm available to help resolve this issue.

**Comment by stevehalliwell** [comment]
Having a look over the existing save code, the only thing that tries to delete the file from storage is the Restart function from the SaveMenu, it also clears all history and notifies of a save reset.

A quick test of the save demo scene doesn't reproduce the issue.

As noted [here](https://github.com/snozbot/fungus/issues/807#issuecomment-608196402) the save system is probably being replaced, but any additional information is appreciated.

**Comment by ianicmathieu** [comment]
There is a Delete Save Data button in the inspector when selecting the SaveMenu object.

while it did work a few times, it stops working after a while.. it's pretty easy to reproduce on my side.
Load the project.
Make sure there is a save file in the User folder.
Press Delete Saved Data.
Result : The file is not deleted.

It's not a big issue, as I can delete the file manually.
