### ISSUE TITLE
Hidden portrait does not reappear in conversation

### ISSUE THREAD

**Issue by jusw85** [snozbot/fungus#811]
**Describe the bug**
Made a [bug report](https://fungusgames.com/forum#!/general:conversation-show-portrait) on Fungus forums on 5th Dec 2017, but hasn't been resolved.

After hiding a portrait in conversation, showing it doesn't appear again if it has the same position and portrait.

**To Reproduce**

1. Go to the scene 'FungusExamples/Conversation/Conversation.unity'
2. Use the following conversation text:
```
john bored left: hello!
john hide:
sherlock eyeroll right: hello!
john bored left: hello!
```
John does not reappear in the final line.

**Additional context**

The following also causes the same issue:
```
john bored left: hello!
john hide:
sherlock eyeroll right: hello!
john:
bored left: hello!
```
but the following **works as intended**:

```
john bored left: hello!
john hide:
sherlock eyeroll right: hello!
john bored:
left: hello!
```

```
john bored left: hello!
john hide:
sherlock eyeroll right: hello!
john left:
bored: hello!
```
It's due to the following if condition which doesn't trigger because hiding isn't recognised as a change which triggers a redraw:

https://github.com/snozbot/fungus/blob/403ceddd7ade13a7a3093dd48347042d54348eb5/Assets/Fungus/Scripts/Utils/ConversationManager.cs#L425

**Versions & Platform**
 - Unity version: 2019.3.7f1
 - Fungus Version: v.3.12.0
 - Editor OS: Arch Linux
 - Build Platform: Linux

**Comment by stevehalliwell** [comment]
Thanks for the detailed case and contribution.
