### ISSUE TITLE
More control for playing audio

### ISSUE THREAD

**Issue by TheEmbracedOne** [snozbot/fungus#821]
It'd be nice if there was more control over playing audio - 
1) when using ControlAudio, you can only select an AudioSource to play, you cant select an AudioClip to play with said AudioSource 
2) when using PlayMusic/Sound/etc you can only select AudioClip, you cannot select AudioSource. These use the MusicManager which creates(?) or uses(?) an existing AudioSource, but you cannot specify which one you want it to use.

It'd be nice if there was a way to add an AudioClip to ControlAudio, so that one can select both the AudioSource and AudioClip to play. Right now, if one wants to have more control over AudioSources Fungus uses to play audio through, the workaround is using different AudioSources for different AudioClips which is not great.

To temporarily bridge this problem, I have added the following modifications to ControlAudio.cs:

`protected SerializedProperty audioClipProp;` to line 17,
`audioClipProp = serializedObject.FindProperty("_audioClip");`  to line 29,
`EditorGUILayout.PropertyField(audioClipProp);` to line 38

(these make it so the AudioClip field appears in the interface as per my screenshot attached)

then in ControlAudio.cs I added,
`[SerializeField] protected AudioClip _audioClip;` in the initial declarations, then every time the _audioSource is played, I pasted this line above it; `_audioSource.Value.clip = _audioClip;`

ideally there should be a better solution to this that is cleaner, but this is my current workaround to it. Hope this is helpful

![Unity_sHJmVDI3M8](https://user-images.githubusercontent.com/16197906/81217019-6ee73280-8fcb-11ea-83a9-bcece25cc717.png)

**Comment by stevehalliwell** [comment]
I'm hesitant to make changes to the existing commands as they are very intertwined into the existing tutorial and structures in examples and users games, given that they setup a relation between sounds, gameobjects and tags.

I'd be all for a suite of more robust commands for dealing with clips and sources though. Can you share your common usages or desired usages for such a system?

**Comment by TheEmbracedOne** [comment]
Hi @stevehalliwell 
I use the "voiceover" entry of SayDialog commands to play voiceover, however any other sound I play I play them through very specific AudioSources because some might use different mixer groups with different effects applies, while some are set to different stereo pans to simulate the sound coming from different locations.

Currently, the two options I have are not suitable because I can either select the sound to play and it defaults to an AudioSource I have no control over, or I can select an AudioSource to play, but if I were to opt for the latter, that'd mean I'd have to set up each audio I'd like to play in the scene with its own AudioSource and then just play those using this command.

A more specific example would be that during a conversation, you may trigger a sound that comes from the environment ie an object audibly breaks; I'd like to play this sound with a mixer with applied effects to it, and play it with an AudioSource with stereo pan towards the left side, and currently both the options that are in Fungus out-of-the-box are not suitable to achieve this, unless I misunderstood something?

Hope this explanation helps. Let me know if you have any questions!

**Comment by stevehalliwell** [comment]
OK so some basic things I'm looking at adding.

- [ ] Fungus Variables for AudioSource, AudioClip, AudioMixer, AudioMixerGroup, AudioMixerSnapshot
- [ ] Expanded properties for AudioSource, so MixerGroup can be set etc.
- [ ] Audio Source Commands, play, playoneshot, stop, pause, resume,
- [ ] Audio Mixer Commands, get set float, transition snapshots
- [ ] Default mixer with groups for music. sfx, voice (existing audio system to default to these)
- [ ] Snapshot transition to

I think that covers your described usage, any addition items that help clean up your use cases?

**Comment by TheEmbracedOne** [comment]
When you say Fungus Variables, do you mean this kind of variable?
![](https://user-images.githubusercontent.com/16197906/81217019-6ee73280-8fcb-11ea-83a9-bcece25cc717.png)
just to clarify, because these are called the same:
![Unity_3EiuHxMEbW](https://user-images.githubusercontent.com/16197906/83134998-b9dcfd00-a0d4-11ea-80b8-ea49a9044f88.png)

The list above sounds great and would not only cover my use cases but add even more functionality I didnt think of before!

If I understand it correctly, this is going into a fork of Fungus, right? How does update from an asset store version of Fungus to a forked version to have these updates once they're done?
Thank you for your great contributions.

**Comment by stevehalliwell** [comment]
Re; type of variable; Both, makes it more flexible for Fungus to use say an AudioMixerGroupData to allow an object from a FungusVariable or directly dragged in from scene.

Not a fork, assuming all goes well, I expect this set of items to be in the next version of Fungus (3.14).

**Comment by stevehalliwell** [comment]
This has been merged into develop now. If you have a chance to look at it and have any additional thoughts, requests, or changes, feel free to reply with them here.

**Comment by TheEmbracedOne** [comment]
wow, great! I'll try to grab it sometime tomorrow!

**Comment by TheEmbracedOne** [comment]
This is great! I no longer need to have a separate SayDialog for each character (to bridge lack of control over each audiosource and mixer).

The Play Source commands are great so far, I have one question though, could we have a Play Source equivalent of Control Audio > Play Loop? Right now to achieve a loop is to use Control Audio > Play Loop right after

![image](https://user-images.githubusercontent.com/16197906/94569281-1277fe80-025d-11eb-92ea-1a3bfa881dd5.png)

I'll do some more testing and post here if I find anything else!

**Comment by stevehalliwell** [comment]
@TheEmbracedOne Yep, can do. I assume that's because you're using the same source for many purposes, so you sometimes want to change the underlying source from looping to non-looping depending on what it's pumping out?

**Comment by TheEmbracedOne** [comment]
Yes, essentially. To give you more context, In my project, I set up a prefab for all audio:
![image](https://user-images.githubusercontent.com/16197906/94803949-90f9ab00-03d9-11eb-9b9e-92f8d2c80888.png)
Essentially there is 2-3 audiosources for each type (music, ambience, SFX) and the audiosources for characters are now on the character objects (the objects that have the Character script).

However, sometimes we want to loop a music or ambience audiosource, while other times we want to only play something once (ie in a cutscene or when a specific thing happens during the game). Right now, the PlaySource commands are exactly what I need, but it'd be neat if I didnt have to use a Control Audio -> Play Loop right after it to make sure the audiosource will loop instead of it being oneshot. 

Maybe it's worth considering making something like this;
![image](https://user-images.githubusercontent.com/16197906/94804366-3a40a100-03da-11eb-8083-4214fe610b64.png)

For the PlaySource commands:
![image](https://user-images.githubusercontent.com/16197906/94804390-44629f80-03da-11eb-99f1-13e590f7aded.png)

(I mean that there would be only one PlaySource command with a Control option, like in ControlAudio's case).

**Comment by stevehalliwell** [comment]
I've pushed a change that allows you to configure the PlaySource command to modify the looping property on the targeted source.  I think that'll fit your use case, while keeping the separation of terms between PlaySource and Control Audio.

**Comment by TheEmbracedOne** [comment]
Thank you, I'll pull it in a short bit!
