### ISSUE TITLE
Token parsing not using specific culture info

### ISSUE THREAD

**Issue by igrir** [snozbot/fungus#822]
I was using Indonesia for my computer's regional format and realized the {vpunch=10,0.5} token 
was longer than usual. 

After debugged the Writer.cs I found out the TryGetSingleParam method was using default parameter for parsing the content.
https://github.com/snozbot/fungus/blob/403ceddd7ade13a7a3093dd48347042d54348eb5/Assets/Fungus/Scripts/Components/Writer.cs#L207-L210

I think it would be better to explicitly determine what culture is being used. I tried to fixed the code with this snippet:

```
protected virtual bool TryGetSingleParam(List<string> paramList, int index, float defaultValue, out float value) 
        {
            value = defaultValue;
            if (paramList.Count > index) 
            {
                var style = System.Globalization.NumberStyles.Number | 
                        System.Globalization.NumberStyles.AllowCurrencySymbol;
                var culture = System.Globalization.CultureInfo.CreateSpecificCulture("en-GB");
                Single.TryParse(paramList[index], style, culture, out value);
                return true;
            }
            return false;
        }
```

**Comment by stevehalliwell** [comment]
Thanks for logging the issue.
Submitted a fix to develop now. There may be other calls that are assuming Culture Info that need to be explicitly provided it though. Please advise if you see further or related issues.
