### ISSUE TITLE
RC1 - Connection between nodes disappears when nodes are out of frame

### ISSUE THREAD

**Issue by ianicmathieu** [snozbot/fungus#823]
**Describe the bug**
When panning or zooming inside the Flowchart, the connection between nodes disappear as soon as a node is no longer displayed.

**To Reproduce**
simply create a few nodes inside the Flowchart, use a Call function to connect them together.

Zoom or Pan to have a node leave the frame. 

Result: The connection link between nodes disappears.

**Expected behavior**
The connection should not diseppear.

**Versions & Platform (please complete the following information):**
 Fungus RC1

**Comment by stevehalliwell** [comment]
Thanks for the report.

Looks like an existing issue unrelated to 3.13 changes. Seems a low risk fix though.
