### ISSUE TITLE
JSON bug when building game

### ISSUE THREAD

**Issue by must-lleibl** [snozbot/fungus#833]
**Describe the bug**
Hi. I am having huge bugs when I building my project with Fungus 3.13.0
It even happens on new empty project

-Assets\Fungus\Thirdparty\FungusLua\Thirdparty\JSON\Editor\JSONChecker.cs(31,28): error CS0246: The type or namespace name 'EditorWindow' could not be found (are you missing a using directive or an assembly reference?)
-Assets\Fungus\Thirdparty\FungusLua\Thirdparty\JSON\Editor\JSONChecker.cs(49,3): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)
-Assets\Fungus\Thirdparty\FungusLua\Thirdparty\JSON\Editor\JSONChecker.cs(49,3): error CS0246: The type or namespace name 'MenuItem' could not be found (are you missing a using directive or an assembly reference?)

-Error building Player because scripts had compiler errors

-Build completed with a result of 'Failed' in 4 seconds (4146 ms)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bb] in <ffcf2f9855fe46038192299154f37a45>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <ffcf2f9855fe46038192299154f37a45>:0 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**To Reproduce**
Create empty 2d project and try to build game. Uning unity 2019.3.12 or higher

1. Import Fungus package into new project.
2. Create new scene
3. File->build settings->Build

**Expected behavior**
After 4-5 seconds you get a cople of errors in Console on building project

**Versions & Platform (please complete the following information):**
 - Unity version [2019.3.12f1]
 - Fungus Version[v.3.13.0]
 - Editor OS: Win 10
 - Build Platform Windows

**Comment by stevehalliwell** [comment]
Thanks for reporting.

Appears to be caused by a change to build process at some point with Editor folders. Should only affect the releases of Fungus that use asmdefs. Working on bug fix releases now. You can also just delete the file causing the error as it is the only one causing problems , only runs in editor, and has zero external references.
