### ISSUE TITLE
Say dialog character image source image sprite name.

### ISSUE THREAD

**Issue by Vaqq** [snozbot/fungus#835]
**Is your feature request related to a problem? Please describe.**
I made a code that checks say dialog character image source image sprite name and does stuff if certain words are in the sprite name. 
![SourceImage](https://user-images.githubusercontent.com/66467367/83865264-a5c97900-a72e-11ea-955b-ebafaef82940.jpg)
With some testing, I only managed to get it to work with Fungus 3.11.4 and with 3.11.5 it did not work. After multiple say commands(in runtime with 3.11.4) you could visually see the sprite name changed in the inspector, game and scene window, and my code worked too. But in version 3.11.5, the sprite name did not change in inspector(name stayed as it was before runtime, but sprite did change in game and scene view) and the code also did not work, as it supposed to. 

I assume it is something to do with, what got fixed in Fungus 3.11.5 (Portrait sprite issue in Unity 2019 #743)

**Describe the solution you'd like**
Is it possible that I could get the say dialog character image source image sprite name to change (like in Fungus 3.11.4), depending on what sprite, say command it's showing.

**Comment by stevehalliwell** [comment]
Most likely your code needs to include in its logic, a check against the image.sprite and the image.overrideSprite. As that was the change made in response to underlying changes in Unity's UI.

Presuming you code looks something like
```c#
if(sayDialog.characterImage.sprite.name.IndexOf("happy") != -1)
{
    //do something cool as the character portrait in the say dialog has happy in its name
}
```
it'll end up something like this
```c#
if(sayDialog.characterImage.sprite.name.IndexOf("happy") != -1 ||
  sayDialog.characterImage.overrideSprite.name.IndexOf("happy") != -1 )
{
    //do something cool as the character portrait in the say dialog has happy in its name
}
```
That should have you covered in code that is both prior to 3.11.5 and after. If you only care newer versions of Fungus and Unity, you only have to check the ```overrideSprite```.

If you are looking to do a similar thing with stage portraits, you'll want to look at PortraitController and the PortraitState class. They both had changes 3.12 and 3.13 releases in response to similar bugs, see also #817.
