### ISSUE TITLE
If command, with float variable won't work.

### ISSUE THREAD

**Issue by Vaqq** [snozbot/fungus#836]
**Describe the bug**
If command, with float variable won't work, it always plays first If command, even if Else If command is below and float variable matches the condition. 

**To Reproduce**
Made a scene with float, integer and string variables(all have identical flows). Float did not work, integer worked and so did string.
[Test_Float_Int_String_Conditions.zip](https://github.com/snozbot/fungus/files/4746522/Test_Float_Int_String_Conditions.zip)

**Expected behavior**
When float variable is changed, correct condition should execute.

**Versions & Platform**
 - Unity version 2019.3.14f1
 - Fungus Version 3.13.1
 -  Win 10

**Comment by stevehalliwell** [comment]
Thanks very much for reporting. Working on hotfix now.
