### ISSUE TITLE
More control for Speaker's AudioSource and default AudioSource

### ISSUE THREAD

**Issue by TheEmbracedOne** [snozbot/fungus#843]
I believe this is somewhat related to #821 but it seems to be a chunk of work so I'm adding it in a separate issue. 

It would be great to be able to set an AudioSource on Say commands, and also to be able to set a Character to default to a specific AudioSource, just like I am able to set their default SayDialogs. For example if I'd like to use a different AudioSource for each character:

![image](https://user-images.githubusercontent.com/16197906/84929749-cc3ccc00-b0bf-11ea-9ac2-4765e3ebaa98.png)

I tried hacking in a temporary solution for this into WriderAudio but it messes with the system and I could not make it work in any way.

**Comment by TheEmbracedOne** [comment]
Current workaround I use: duplicated the SayDialog I used, one copy for each character with its own AudioSource on it, so that when the SetSayDialog defaults to them, they all use different AudioSources now, however this messes with the "Fade when done" option, text will overlap when speaker changes.

**Comment by stevehalliwell** [comment]
Good suggestion. Having the option to specify an audiosource for a character could be quite useful. I'll bundle it together with the existing audio additions.

**Comment by TheEmbracedOne** [comment]
Many thanks @stevehalliwell and keep up the great work! Could you let me know if you have a rough estimate of when 3.14 might be out?

**Comment by stevehalliwell** [comment]
Sorry, don't have a date for you, but 3.14 is now at the point of trying to get it tested by users and stable.

This has been merged into develop now.
