### ISSUE TITLE
Punctuation Pause and writer audio are not functional with TextMeshPro UI components

### ISSUE THREAD

**Issue by Ayreos** [snozbot/fungus#845]
**Describe the bug**
The settings of punctuation pause and writer audio in the Writer component don't work anymore.
In Writer.cs the condition "if (textAdapter.SupportsHiddenCharacters())" is always true when using textMeshPro, which prevents the punctuation pause and other writer code from ever running in its "else" branch.

**To Reproduce**
Setting any value of punctuation pause or any type of writer audio sounds will not produce any result for the former and play a single sound once for the latter. This occurs in the TMPro demo scenes as well.

**Expected behavior**
Appropriate pauses would be performed when encountering punctuation in 3.10 on Unity 2019.1, and writer audio would perform a different sound for each character displayed.

**Versions & Platform (please complete the following information):**
 - Unity version 2019.4.1f1
 - Fungus Version 3.12.2
 - Editor OS: Win 10
 - Build Platform WebGL

**Comment by stevehalliwell** [comment]
Thanks for reporting. 
Fix for this and some related TMPro specific gremlins coming in 3.13.4
