### ISSUE TITLE
Saving Variables when you use Set Variable, Loading Variables on If/ElseIf/Else

### ISSUE THREAD

**Issue by TheEmbracedOne** [snozbot/fungus#846]
Possibly related to #795 

I've been experimenting with loading and saving and variables and realised that unless I'm doing something wrong, variables arent getting saved and loaded the way one would expect.

### Saving Variables
Case example, in a test scene:
1) have a block at the start with Set Variable in it, where you set "Var" to true.
2) Call to a new block where you have a SavePoint (this is the block the game resumes on)
3) restart the build, select the test scene to load in the main menu
4) game loads to the abovementioned block, Var will be false 

The only way to have Var be true on loading the scene is as follows:
1) have a block at the start with Set Variable in it, where you set "Var" to true.
2) Right after the Set Variable command, have a Save Variable command, key = Var, Variable = Var for testing's sake
3) Then, after the save point (that the game will resume at), have a Load Variable command, key = Var, Variable = Var
4) restart the build, select the test scene to load in the main menu
5) game loads to the abovementioned block, Var will be false 

Supporting screenshots:
![image](https://user-images.githubusercontent.com/16197906/85926365-8be30800-b88e-11ea-845b-d9d4d3e8fe83.png)
![image](https://user-images.githubusercontent.com/16197906/85926369-900f2580-b88e-11ea-8e51-632e72d4c8d7.png)
![image](https://user-images.githubusercontent.com/16197906/85926375-98676080-b88e-11ea-8343-3b7028ffd579.png)

### Loading Variables
Obviously, with the above in mind, if the player were to quit the game during play and reload to a Save Point (with autosave), If/Else/ElseIf checks will fail unless you manually load each variable every single time. Case example, above cont.:
If on the block that the game loads on using the autosave, there is an if check for Var being true or false, unless I have the Load Variable command to load the variable, it'll always be true since it does not save variables after setting them:
![image](https://user-images.githubusercontent.com/16197906/85926465-30654a00-b88f-11ea-94cc-fdd7d8051a59.png)

Maybe me use cases are different, but I would expect variables to be saved immediately on Set Variable, and the relevant variables being loaded on any If/ElseIf/Else commands. 

Please let me know if I'm doing something wrong or if I'm supposed to use Save/Load variables every time? If the latter, I'll need to figure some workaround by modifying the Set Variable, If, ElseIf and Else command scripts so the relevant methods are called when necessary. Please advise @stevehalliwell

**Comment by TheEmbracedOne** [comment]
Could you advise me on how I would go about:

* calling the SaveVariable command from within the SetVariable script
* calling the LoadVariable command from within the If, ElseIf and Else scripts to load variables (although it might be enough to only add this into the If.cs)

I'm guessing in the case of the Ifs, the call would need to go in the OnEnter() and in the case of SetVariable, into DoSetOperation(), but I cant figure out how to "feed" the SaveVariable/LoadVariable the relevant variable information.
Thank you

**Comment by TheEmbracedOne** [comment]
[WIP] Consolidate and Extend Save System #795 covers this issue

**Comment by TheEmbracedOne** [comment]
Originally added

**Comment by stevehalliwell** [comment]
Perhaps confusingly, Save and Load variable commands are not refering to Fungus's save system (the existing or future one). They call directly down to PlayerPrefs, with a prefix added to indicate user SaveProfile and a substitutevariables call so they can be a little more flexible.

The hope is that with the improvements in the new save system you won't find the need to use both the save system and playerprefs to get the behaviour you are seeking. The save system alone will get it done.
