### ISSUE TITLE
An error occurred when Domain Reloading disable

### ISSUE THREAD

**Issue by yano** [snozbot/fungus#848]
**Describe the bug**

When disable Domain Reloading, Fungus throws the following error.

ArgumentException: An item with the same key has already been added. Key: -115084556

![funguserror1](https://user-images.githubusercontent.com/24616900/86447343-2c826d80-bd50-11ea-86cd-84347d14cb91.png)

**To Reproduce**

1. In Unity version 2019.3.13f1, create empty project. (Editor OS Win10, Build Platform Win)
2. Import Fungus version 3.13.2.
3. disable domain reloading
![funguserror2](https://user-images.githubusercontent.com/24616900/86447678-aa467900-bd50-11ea-90ee-ee046da5771b.png)
4. press play button

**First aid**
I modified TMProLinkAnimLookup.cs's static functions like this:

```
        static public void AddHelper(string linkIdText, TMProAnimFunc func)
        {
            //LinkHashToEffect.Add(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText), func);
            
            if(!LinkHashToEffect.ContainsKey(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText)))
                LinkHashToEffect.Add(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText), func);
        }

        static public void AddHelper(string linkIdText, TMProLinkAnimEffects.BaseEffect baseEffect)
        {
            //LinkHashToEffect.Add(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText), baseEffect.DoEffect);
            
            if(!LinkHashToEffect.ContainsKey(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText)))
                LinkHashToEffect.Add(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText), baseEffect.DoEffect);
        }

        static public void Remove(string linkIdText)
        {
            //LinkHashToEffect.Remove(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText));
            
            if(LinkHashToEffect.ContainsKey(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText)))
                LinkHashToEffect.Remove(TMPro.TMP_TextUtilities.GetSimpleHashCode(linkIdText));
        }

```
The error disappeared.

**Comment by stevehalliwell** [comment]
Thanks for the report and existing work around. Testing of Domain Reload Disabled with Fungus has not been done yet. But I'll put through your suggested changes here as a bugfix.
