### ISSUE TITLE
Performance issue within the plugin

### ISSUE THREAD

**Issue by breadnone** [snozbot/fungus#850]
Massive performance hit with complicated scenes with a lot of animated objects. Tested with current project (made with latest Unity)I also opened my old project from 2017/2018 the problem persists (it wasn't like that when I developed those projects before).

Made my own test scenario by hardcoded/tested everything without Fungus with the same amount of objects, no noticeable slowdowns or anything.

Re-formated my pc and fresh installed, still, the problem persists.

This perhaps Unity's fault but I thought I could just drop it here for further investigation.

Cheers~

**Comment by stevehalliwell** [comment]
Thanks for reporting. If you find any more specifics let us now here. I suspect the changes Unity is making to the underlying code for EditorUI rendering is the cause, I've noticed some performance problems related to the inspector in projects without Fungus too.
Could be related to #849

**Comment by breadnone** [comment]
That pretty much solved the issue even though I'm still experiencing stutters in the editor but after looking at Unity's bug reports, I guess I'm not alone.

Thanks for the response, cheers
