### ISSUE TITLE
If a character name string starts with another character name string, CreateConversationItem will always pick the first in the list

### ISSUE THREAD

**Issue by hsandt** [snozbot/fungus#854]
Runtime bug when ConversationManager.CreateConversationItem parses the conversation text of a Conversation command.
Because it relies exclusively on NameStartsWith, a character name that is at the same time a full name for one character, and the start of a name for another character is ambiguous.

Ex: There are two characters, Daniela and Daniel, _registered in this order_ in the Characters list.

1. The conversation line "D: Hello!" will make Daniela speak. It's fine, since D is ambiguous, Fungus has to make a choice and will pick the first character whose name starts with "D" in the list.
2. The conversation line: "Daniel: Hello!" will make **Daniela** speak. This is because only the name start is checked, and Daniela is first in the character list.

**To Reproduce**
1. Define characters "Daniela" and "Daniel" in this order
1. Create a Flowchart with a Block with a Conversation command "Daniel: Hello!"
2. Add a simple way to trigger the Flowchart (e.g. on Start)
3. Play the game
4. See dialogue: Daniela says "Hello!".

**Expected behavior**
The dialogue shows Daniel say "Hello!".

**Versions & Platform (please complete the following information):**
 - Unity version: 2018.3.6f1
 - Fungus Version: v3.11.0 (it's old, but I've just checked ConversationManager.cs in master branch and this part didn't change)
 - Editor OS: Linux (doesn't matter)
 - Build Platform: Linux (doesn't matter)

**Additional context**
Suggestion solution:
- create method `Character.NameMatches(string)` that checks exact match
- in `ConversationManager.CreateConversationItem`, when you iterate on characters, replace the character loop with this code:
```cs
for (int j = 0; j < characters.Length; j++)
{
    if (characters[j].NameStartsWith(sayParams[i]))
    {
        if (characters[j].NameMatches(sayParams[i]))
        {
            // found exact match, exit loop now
            characterIndex = i;
            item.Character = characters[j];
            break;
        }
        else if (characterIndex == -1)
        {
            // this is the first character with name start matching (but not full name string)
            // store it for later but continue the loop in case we get an exact match
            characterIndex = i;
            item.Character = characters[j];
        }
    }
}

**Comment by stevehalliwell** [comment]
Thanks for reporting, I'll follow this up in the next few days.

**Comment by stevehalliwell** [comment]
I've made a test scene as per description and haven't found the exact behavior you've described. Characters were not always sorted by name which may have changed the bug. I have found that if we have a number of characters all called john with different last initials we can get the partial match confused.

Your proposed solution looks solid, I'm going to go a step further and warn the user if the exact match fails.

**Comment by hsandt** [comment]
Ah I see, in this case yes you'd want something like Donatella, Donatelli and Donatello since shorter names must be alphabetically placed earlier, and try "Dona: hello!" 

The fix looks good anyway. It forces the user to use full name or nameText to remove warning, but I think name v nameText is here for that reason: you can use a unique short name identifier like "ji" for "John Ingleston" if you prefer, so you only use "ji: hello!" in a conv.

Should we wait for next release to close this issue? (the commit will get merged into master, triggering the Fix keyword automatically anyway)
