### ISSUE TITLE
Vector3 block: setting the property does not work

### ISSUE THREAD

**Issue by happyturtle5** [snozbot/fungus#855]
**Describe the bug**
I tried to use the vector3 block to set the Y-value of a vector3 variable with a float variable, but the Y-value did not change.

**To Reproduce**
-Make a flowchart
-In the flowchart, make a Vector3 variable
-In the flowchart, make a float variable and set it to 5 (or any other value)
-In the flowchart, create a block that starts when the game starts
-In the block, create a Vector3 block
-In the Vector3 block:
--Get or Set: set
--Property: Y
--Vector 3 var: YourVector3
--InOutVar: YourFloat
-Stat the game
-in the flowchart, look at the vector3 variable and see that it is still 0,0,0

**Expected behavior**
the vector3 variable should show 0,5,0 when the game starts

**Screenshots**
-

**Versions & Platform (please complete the following information):**
 - Unity version 2019.4.1
 - Fungus Version 3.13.3
 - Editor OS: Win 10
 - Build Platform: in Editor

**Additional context**
The "fields" block works for that, so its not a huge problem. But it is indeed confusing that there are 3 ways to set a vector3 variable, one with set variable, one with Vector3 and one with Fields and having one not working

**Comment by happyturtle5** [comment]
![grafik](https://user-images.githubusercontent.com/13916751/88338238-5cfa6d80-cd38-11ea-8ba8-3073f74a465b.png)

**Comment by stevehalliwell** [comment]
Thanks for reporting, I'll follow this up in the next few days.

**Comment by stevehalliwell** [comment]
Issue was caused by a missing write back of local value to source FungusVariable in Property Commands that operate on value types rather than reference types.
