### ISSUE TITLE
Fungus 3.13 Compatibility Version's TMPro requirement Breaks Compatibility with Unity 2017

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#860]
**Describe the bug**
Upon upgrading a Fungus 3.13 project to Unity 2018, I got errors about how TMPro's namespace couldn't be found. That itself was simple enough to fix with this version of Unity, but it's simply unfixable in any version of Unity 2017; none of those come with TMPro.

I've tried opening that same project with 2017 before the upgrade, and each and every time, it crashed. This could be part of the issue.

This same issue also happens with the compatibility version of Fungus 3.12.

**To Reproduce**
1. Create a new project with any version of Unity 2017
2. Import the latest Fungus 3.13 compatibility package into it
3. Look at the console

**Versions & Platform**
 - Unity 2017.4 LTS/2018.4 LTS
 - Fungus 3.13.3 Compatibility Version
 - Editor OS: Windows 10
 - Build Platform: N/A

**Comment by stevehalliwell** [comment]
So I made a new empty 2017.4.40f1 project and imported the latest from the 2017.4 branch (as a package) and not run into the same issue you are describing. Had 1 expected warning in the console and TheExperiment demo ran as usual. I also did a quick check of the 3.13.0 compat, it behaved similarly.

Unity Version: 2017.4.40f1
Fungus: latest from 2017.4 branch + merged in changes from current develop
OS : Windows 10

Can you think of any additional details about your setup to share that might be different here. Also can you copy paste (or screenshot) the exact errors you are getting in the console, as all references to TMPro should be wrapped within '#if unity version greater than x' checks.

**Comment by CG-Tespy** [comment]
Did the same thing the other day, and things were indeed just fine... Huh. Also, upon further tinkering, it turned out that the crash wasn't Fungus's fault. 

My bad, I misunderstood ^^;
