### ISSUE TITLE
Saydialog TMPro text UI component error.

### ISSUE THREAD

**Issue by Vaqq** [snozbot/fungus#862]
**Describe the bug**
Bug during playback. Flow stops on the say command, gives an error and won't let you click to advance. Worked fine with Fungus 13.2 and after 13.4 update it stopped working.

**To Reproduce**
Updated Fungus to 13.4. Tested with Fungus saydialog (prefab asset) and worked like it should, but when I made custom saydialog that contains TextMeshPro - Text (UI) component and with that, it gives an error.

**Expected behavior**
Say command should let you click and advance to the next command and no error.

**Screenshots**
![Error_1](https://user-images.githubusercontent.com/66467367/90956278-ba93ee00-e48d-11ea-9e33-2e5ccda68071.png)

**Additional context**
TextMeshPro ver. 3.0.1
Unity 2020.1.0f1

**Comment by stevehalliwell** [comment]
Thanks for the extra info, I'll be able to chase this down in the next few days.

**Comment by stevehalliwell** [comment]
also noted here https://fungusgames.com/forum#!/general:i-got-something-about-the-t
