### ISSUE TITLE
The Option for using Addressables in Character Sprites

### ISSUE THREAD

**Issue by danac78** [snozbot/fungus#865]
**Is your feature request related to a problem? Please describe.**
Currently, I can have the background using raw image use addressable using C#. However, such a feature isn't current;y available with sprites because the command/component currently has Sprites rather than String (which would attach the sprite based on an addressable table a user creates.

**Describe the solution you'd like**
Overall, it isn't challenging to implement addressable (I think).  How I did it for the textures for backgrounds:
using UnityEngine.AddressableAssets;
using UnityEngine.ResourceManagement.AsyncOperations;

SomeMethodtoCall(string Address)
Addressables.LoadAssetAsync<Texture>(Address).Completed += OnLoadDoneTexture;

    private void OnLoadDoneTexture(AsyncOperationHandle<Texture> texture)
    {
        try
        {
            panel.texture = texture.Result;
        }
        catch
        {
            Debug.Log("Texture Not Found Likely");
        }
    }
----
The above is only an example of working code. I have not applied it to setting up against the stage.positions etc. Overall, you can create a separate command for Sprite For Address, and have the sprite on the complete go into the stage.positions.

**Describe alternatives you've considered**
I have considered doing it myself which would likely result in: A. screwing it up or B. having to redo it everytime fungus is updated. The reason for this is to improve asset management and loading only the sprite image needed rather than having them all sit in memory. :)

**Comment by danac78** [comment]
Just a followup:
The statement to Add Addressibles to the Fungus asmdef did make me see something, and something that might make the option even more viable. If I understand the flow right, the TextMesh enables the Textmesh GO option for the Say Dialog Box. So, something similar could be used where someone will put in the string name of an asset (or assetreference, which ever)..and the engine goes with that.

If you do decide to enhance with this, I do recommend no higher than 0.8.4 of the Addressable package. I tried higher, but..things went..very wrong. Things that despite going through a tutorial caused unexpected behavior, and I reverted to 0.8.4 to get the system to work. :)

**Comment by stevehalliwell** [comment]
Addressables are definitely an area of interest, the main points in my mind are: 
Should every location that currently takes an asset reference support an Addressable instead/aswell?
How do we present the options of direct reference vs addressable to users?
This should wait until after 3.14, it's already HUGE.
This should wait until after Fungus no longer actively supports 2017, to avoid the extra headache of putting all of the new elements inside #if UNITY_2018_4_OR_NEWER

**Comment by danac78** [comment]
To answer some of them:

1.	No problem with waiting until after 3.14, and agree with the 2018 issue. 
2.	I think other areas should depend on how much it is intertwined with Fungus. For example, I have the Background, Videos, and Prefabs programmed into a C#, and use the Invoke Method to call them. If I understand one of goals of Addressable right, it is to stop the massive loading in the beginning of ALL assets with only assets that needed at a time. It also unloads them from memory, which becomes essential with certain visual novels. :) However, Portraits are tied to Character, and other scripts I got lost trying to figure out, and would mess up. So, I think the title should be change to "Character Portrait Sprites."
3.	As Addressable require:
a.	 Planning: It involves a little more than installing Addressible packages. You need to should make groups to organize the assets, and then remember the names. I have tried using AssetReference, but wouldn’t work for me so I went with just using strings as an address which is fine.
b.	Working with the Addressable package.
I don’t think it is necessary to make it default use for general users. However, I was thinking along the lines of similar commands in Fungus with like “Addressable Characters” that collect string. Possibly a Addressable Conversation and Portrait since I believe the two now look sprites, which would cause a conflict. Unless there is an easy way (still new to C#) to take an obj and tell if it is a sprite or a string. This would make it an option for users who wish to utilize it rather than forcing everyone else to do it.

**Comment by danac78** [comment]
Changed it so it is a little clearer. Like I mention above, backgrounds, prefabs, videos, and sounds are easy to just C#, apply to a game object, prefab the game object, and put it in the scenes. That is how I am doing most of my addressables now, and easy to implement with Fungus Invoke Method/Invoke Event (not sure why some items don't do well in Event..I think Unity just hates me somedays because it changes its mind).  Character sprites, on the other hand, are tied into different Fungus scripts, and would create an issue if 1. I mess it up (high chance) and 2. if there is update because I have to implement it again. 

The reason: If I am understanding Unity right, it will load everything in SharedAsset files first, and then play the scene (which is fine). Right now, my character files are smallish because I only have a few images for each character, but there are multiple chapters and I have different outfits that these characters will appear as (for example Lily will appear one way in a regular occurrence, but another when she is running a club). I would rather keep all her images in one character, prefabbed, so I can drag and drop if all possible without issues.

Another scenario is using one scene with multiple flowcharts to tell an entire story. If I understand the difference between direct reference and addressables, the former doesn't leave memory even if you are done with it. So if someone has 48 images for their character, that would be 48 images that may or may not be used all the time. Whereas with addressable, you call the image you want to use, it plays, and then unloads out of memory. However, like I mention above, takes a little planning and beginners may not be up to that stage yet. That is also why I say an Option (probably an extra command.

Another idea that popped into my head that may be a solution to keep the command list small..a toggle. For example, you create a character object. If you click on a checkbox for Addressable, it will create an array for strings, where unchecked (or whatever) will do the sprite references.

**Comment by danac78** [comment]
@stevehalliwell Even though this would only affect 4 C# scripts (I think?), I still agree with your assessment of 2018.

**Comment by danac78** [comment]
@stevehalliwell ok, found the error message that would occur if you try to use AssetReference...at least in the flowchart. "Cannot be drawn, don't use Flowchart for this"

**Comment by danac78** [comment]
@stevehalliwell Just to log for future reference:
It is possible to use AssetReferences in a list/array/etc without error messages. This is an example for my handling of sound addressable that an idea popped in (but still not sure how to tie it into portraits):

private IEnumerator LoadMusicClip(int RefID)
    {
        AsyncOperationHandle<AudioClip> audiocliphandle = musicReferences[RefID].LoadAssetAsync<AudioClip>();
        yield return audiocliphandle;
        if(audiocliphandle.Status == AsyncOperationStatus.Succeeded)
        {
            music.clip = audiocliphandle.Result;
            music.Play();
            Addressables.Release(audiocliphandle);
        }
    }
RefID is an int, which I made to identify an asset in an array. Between AssetReference and String, the former might be better because one doesn't have to search the entire Addressable Groups to see what the name is, copypaste, and such. It will just appear in the box. :)

**Comment by danac78** [comment]
Saw this because I was wondering if it was possible:

https://answers.unity.com/questions/192895/hideshow-properties-dynamically-in-inspector.html

As I mentioned above, Addressable may not be for everyone. So something like what this thread did might be helpful to switch between direct references and addressable. :)

**Comment by danac78** [comment]
https://fungusgames.com/forum#!/general:commands-sprite-variable-a
