### ISSUE TITLE
A way to Change Color of Commands

### ISSUE THREAD

**Issue by danac78** [snozbot/fungus#868]
**Is your feature request related to a problem? Please describe.**
Some colors schemes can hit individuals differently. On some days, the If/Loop/etc commands color (yellow) shows up as an irritant for light sensitivity. While Wolfrug is correct I could change it myself, this would create a problem when Fungus updates, so that is not a practical idea.

**Describe the solution you'd like**
One idea would be create a few color schemes to select from the Tools>Fungus window, so users can quickly change to that even after updating.

**Comment by stevehalliwell** [comment]
I think it would be low impact to introduce a global tint for the command list in the block inspector. Allowing user to darken or tint all blocks without requiring a large code change, new systems, or invalidating doco.

Longer term, I think removing get colour from the command and moving it into the command attribute along with a command/command category colour lookup is a good idea here. Could then also allow users to override individual commands or categories of commands colours via the FungusSettings.

**Comment by breadnone** [comment]
I'm working with mostly dimmed screen and this feature would be a great addition for fungus

**Comment by stevehalliwell** [comment]
@danac78 I've put together the first part of my suggestion here #875. Let me know in that PR if there are more elements I should look at incorporating.
