### ISSUE TITLE
Cannot push new branch to repo

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#888]
I've created a new branch from upstream/develop for a new feature: automatically changing text fields' fonts based on what the current language is. I've managed to get it working, and I wanted to submit a PR, but for some reason, I get Authentication Failed errors. I don't know if it's Github or this repo's settings, but I figured I should bring this to your attention.

**Comment by breadnone** [comment]
Most probably the remote branch has been updated. Repulling and then push should do the trick. Hopefully :)

**Comment by CG-Tespy** [comment]
Sadly, doing that didn't work. I even tried rebasing, to no avail. Thankfully, I managed to get around the issue by making a new branch off the one with the new feature, and making a PR off of that.
