### ISSUE TITLE
The Set Variable and If commands don't properly show ObjectVariable data

### ISSUE THREAD

**Issue by CG-Tespy** [snozbot/fungus#893]
**Describe the bug**
When you set a variable for these commands to work with, the Data field just shows empty lines.

**To Reproduce**
1. Create a Flowchart with two ObjectVariables
2. Add a block with a Set Variable command
3. Under Conditions, set the variable to one of the ObjectVariables in the flowchart
4. See as the Data field is empty
5. You'll get similar results when doing this with the If command

**Expected behavior**
The data field for ObjectVariables to let you select wither a variable or a specific Object

**Versions & Platform (please complete the following information):**
 - Unity version: 2020.1.4f1
 - Fungus Version: 3.14
 - Editor OS: Win 10
 - Build Platform: Standalone

**Additional Context**
The same issue happens with custom variable types.

**Comment by pansam14** [comment]
If this helps, it looks like the object variable is just missing its propertyDrawer. Duplicating GameObjectVariableDrawer and just rewriting stuff to use Object solved this for me.

**Comment by CG-Tespy** [comment]
@pansam14 Thank you very much! That solved the issue for me as well ^_^
