### ISSUE TITLE
Say command's text skips ahead, based on previous Say command's text length

### ISSUE THREAD

**Issue by TheEmbracedOne** [snozbot/fungus#910]
**Describe the bug**
My Say dialogue's Writer script is set to NOT write whole words, NOT instant complete, NOT do read ahead text, while writing speed was set to 30, yet, when the next Say command's text is displayed, it skips ahead. See gifs below. 

**To Reproduce**
1. Create a scene with the following setup: 
**Say dialogue**
fade duration: 1

**Writer**
writing speed: 30
write whole words: off
instant complete: off
do read ahead text: off

Make sure both Say commands are set to "Always Show" and untick "Fade When Done". Menu commands should NOT be "Hide if Visited".

**Commands**
- First node to have a Say command and a Menu command that leads to the second node
- Second node to have a Say command and a Menu command that leads back to the previous node. 

2. Enter play mode, click the menu option, observe the text being written out and remaining onscreen.
3. Click the menu option to go back to the previous node.
4. Click the menu option again, observe text not being written out, but instead some of it appearing onscreen, as if the previous Say command's text's length affected it. See gifs below.

**Expected behavior**
Text in Say commands set to "Always Show" to be written out from scratch every time they're displayed.

**Screenshots**
Say text skipping ahead based on previous Say text's length:
![ePmo1eXO0P](https://user-images.githubusercontent.com/16197906/97114063-2db41d80-16e6-11eb-882d-86cd292a0c61.gif)

Same thing, but I made the first Say text 1 character. Observe the difference:
![grkK4dggon](https://user-images.githubusercontent.com/16197906/97114303-98b22400-16e7-11eb-886b-022f1f0a7a09.gif)

Here, you can see the same text being displayed for the first time, being written out, then second time, it doesnt get written out, it just fully appears onscreen. It would be expected that it always gets written out from scratch like first time:
![TCe9kG1Vjm](https://user-images.githubusercontent.com/16197906/97113922-4a038a80-16e5-11eb-80b5-b78b5f1377fa.gif)

**Comment by breadnone** [comment]
Confirmed, I've this issue with texts instantly revealed right after interacting with menu dialog

**Comment by breadnone** [comment]
Man, this problem is all over my game now... Tried to track it down but found nothing

**Comment by TheEmbracedOne** [comment]
Unfortunately the pr by @breadnone #952 hasnt fixed the issue - here's a slower gif to demonstrate:
As you can see the first text "The ship Cormo was sitting in for two days" is quite long, and then, after selecting the menu option AFTER this text, the next text will start at this point:
![UnwtcQ1szK](https://user-images.githubusercontent.com/16197906/112736360-08a03100-8f4a-11eb-846a-c06982e8122e.gif)

but if I replace the "The ship Cormo was sitting in for two days" text with "Short", observe the change:
![GriXTfbyph](https://user-images.githubusercontent.com/16197906/112736414-47ce8200-8f4a-11eb-907d-77dd32463d45.gif)

Hope this demonstrates the issue better!

**Comment by breadnone** [comment]
I'm not sure why it doesn't fix it for you, the bug never appeared in my game anymore with that pr. Make sure you git cherry-pick the pr and not manually adding them to your script, incase you missed something.

Another thing you could try is after adding that PR, then  setting the DialogInput to false while your menu is up, then wait for next frame and set it back to true after the menu gets clicked. That said, Fungus doesn't have anything to handle input buffer, so I guess that's the issue

**Comment by TheEmbracedOne** [comment]
@breadnone I've just triple checked the PR, I've got all the changes from it (compared my version and yours in WinMerge too), and I even removed all the DialogInput components from everything and the same problem still persists.

**Comment by stevehalliwell** [comment]
OK, so I found a simple repro. And, I found putting a Wait 1 Frame on the block that is being called by the menu removed the issue in my simple repro scene. 

While that's not a good solution, it would be helpful if you can test the same in your circumstances, so I can rule out that I found an unrelated bug.

**Comment by TheEmbracedOne** [comment]
Thanks, I'll try this asap and report back on the results!

**Comment by TheEmbracedOne** [comment]
@stevehalliwell Thank you so much, this seems to have completely fixed the issue!
