### ISSUE TITLE
How to expose args/params of the InvokeEvent command?

### ISSUE THREAD

**Issue by TheEmbracedOne** [snozbot/fungus#918]
This is yet another quality of life thing i'm pursuing. I managed to expose the parameters of the InvokeMethod command, so that it displays in the command's summary, like this:
![image](https://user-images.githubusercontent.com/16197906/98570138-fd09e180-22aa-11eb-9225-f4a70612d226.png)

I achieved this by replacing
`return targetObject.name + "." + targetComponentText + "." + targetMethodText`
with 
`return methodParameters[0].objValue.stringValue;  `

I'd like to do the same for InvokeEvent, to achieve this, for the static event:
![image](https://user-images.githubusercontent.com/16197906/98570484-6984e080-22ab-11eb-8c13-1426e28c2530.png)

I've tried everything in the GetSummary function of the InvokeEvent.cs script, I've exhausted pretty much all of the IntelliSense suggestions there were to the values declared in the command to no avail, I cant figure out how to get the parameters to display like that. If anyone could let me know how to do this, I'd appreciate it.

**Comment by breadnone** [comment]
The first is statically typed, the latter is generated at runtime. You can't get the index of array without it's being executed first :)
