### ISSUE TITLE
Portrait Dim error

### ISSUE THREAD

**Issue by AlejandroLaraEsp** [snozbot/fungus#922]
https://youtu.be/EL9uNAxR6CU
This problem happens because, for some reason, if the first image is the same as the final, The final image doesn't show properly. The only solutión that I found is a fake solution. I made a copy of the image and rename it. By that way Fungus take it as a different image. But is only a patch, The error is still there. This bug is present in the "Sherlock" example after you decide don't drink the coffee.

To reproduce the error you only need to play.
https://drive.google.com/file/d/1Zc_yRLMaRSBWQ88PZ-0U2XQ0AcO-MzHx/view?usp=sharing

**Comment by breadnone** [comment]
Same bug can be seen in "Sherlock - The Experiment" sample project, right after you choose "Don't drink the Coffee" the very first dialog will have John & Sherlock portraits both in undim state

**Comment by broodysky** [comment]
I found it occurred when I tried to let the same character speak and used different portraits. Besides, the second portrait had been dimmed before.

According to the code in "SayDialog.cs", if you don't change a speaker or the character is in the same dimmed state, the portrait won't change color.

**Comment by stevehalliwell** [comment]
There's a PR open now to solve the reported case in 'The Experiment' demo scene. If others are able to confirm that the change fixes there issues too that would be much appreciated.

**Comment by breadnone** [comment]
Tested this on my ongoing project https://breadnone.itch.io/ayas-loop ...All dim issues are gone.

Finally!
