### ISSUE TITLE
MusicManager.cs  audiosource Music, Ambiance and Effect should all have separate volume access 

### ISSUE THREAD

**Issue by ianicmathieu** [snozbot/fungus#927]
Presently, using the available Fungus command Set Audio Volume, sets the volume for Music, Ambiance and Effects at the same time.

We should be able to use different commands to adjust the volumes individually since we are already managing those sound source individually.

**Comment by breadnone** [comment]
This was done in https://github.com/snozbot/fungus/pull/847

**Comment by stevehalliwell** [comment]
This will be part 3.14. It's in develop should you wish to try it out and log feedback/issues regarding it's in develop state.
