### ISSUE TITLE
Flowchart block show as empty on the Inspector in Unity 2019LFS + Fungus 3.10.0

### ISSUE THREAD

**Issue by ramesh-poreddy** [snozbot/fungus#933]
We upgrading our unity project 2018.4.5 to 2019.4.16. We are using fungus v3.10.0. When we upgrade unity, all the blocks in the project show as empty on the inspector. Please check the attached images for the same. 

![2018](https://user-images.githubusercontent.com/76210348/102613432-78876a00-4158-11eb-9122-a57c4a85975d.jpg)
![2019](https://user-images.githubusercontent.com/76210348/102613439-7a512d80-4158-11eb-8571-71542e9d1a45.jpg)

**Comment by danac78** [comment]
It is difficult to tell what may be happening, or if it had already been corrected.

https://github.com/snozbot/fungus/releases/tag/v3.13.6

Please delete the fungus folder and fungus example folder if there, download the fungus release in the link above, and install. It will not affect the flowcharts in the Unity File, but it should help resolve the issue.

**Comment by Arylos07** [comment]
This happened to me before; many of the Editor UI scripts were incompatible with the new inspector. Updating to at least 3.10 should fix the issue or try reimporting fungus.
