### ISSUE TITLE
Flow/For and Flow/LoopRange are the same!

### ISSUE THREAD

**Issue by breadnone** [snozbot/fungus#975]
**Describe the bug**
Duplicate commands. Flow/For vs Flow/LoopRange.

Different names with same functionality.

**Comment by stevehalliwell** [comment]
This isn't a bug it's intentional.

https://github.com/snozbot/fungus/blob/4b65dc42328b1048f8c46acda9ff5cc75a4f1985/Assets/Fungus/Scripts/Commands/LoopRange.cs#L11-L18
