### ISSUE TITLE
Unity's default RichText tags Cause Scrabbled text

### ISSUE THREAD

**Issue by breadnone** [snozbot/fungus#977]
**Describe the bug**
When using RichText with Unity's default text component (Non-TMPro), tags such as bold, italic would show scrabbled texts for split seconds.

Some other things may contribute to this problem, as my project is heavily using postprocessing, lightings etc...

**To Reproduce**
Add any RichText tags such as bold, italic or anything from your SayDialog

**Expected behavior**
Should display text properly

**Screenshots**

**Versions & Platform (please complete the following information):**
Latest Fungus version(git).

**Comment by wolfrug** [comment]
This is what the curly-brace tags are for {i}, {b}, {color=black} etc. :)
