### ISSUE TITLE
Feature Request: A toggle to have blocks align to a grid.

### ISSUE THREAD

**Issue by Ray2r** [snozbot/fungus#978]
Multiple blocks can become quite an OCD experience since they can drag and drop anywhere. 

**Describe the solution you'd like**
Since there exists a grid in the flowchart menu. I would like an on/off toggle that can align the start, center, or end of the block being dragged on a gridline. A good example would be how it looks in a vertical layout group. Turning off the toggle will have block drag and drops perform the same as it does right now.

This way, not all blocks need to be aligned. Only the ones you want aligned needs to be align. Such as performing a call for if Integer = 1, 2, 3, 4, 5, 6, 7. And each one would call it's own block.

**Comment by breadnone** [comment]
Fungus has Grid Snap which you can toggle via Project Settings

**Comment by Ray2r** [comment]
Perfect, thank you!
