### ISSUE TITLE
TextMesh Pro Sprite Rich Text Support

### ISSUE THREAD

**Issue by addie-lombardo** [snozbot/fungus#979]
**Is your feature request related to a problem? Please describe.**

I'm currently trying to implement support for [TextMesh Pro's inline sprites](http://digitalnativestudios.com/textmeshpro/docs/rich-text/#sprite) but am stuck on how to append the text I've generated to appear in the final string that appears on screen because it does not requite a open and close tag (ex. `<size> </size>`)

**Describe the solution you'd like**

Inline sprites should render without requiring the Writer to print out the full rich text string 
![image](https://user-images.githubusercontent.com/25385583/121285528-65499180-c893-11eb-951b-9c37a6a5e23d.png)

**Additional context**

<img width="473" alt="rider64_UcdnnFTZcL" src="https://user-images.githubusercontent.com/25385583/121282412-50b6ca80-c88e-11eb-84fb-ac2741be84c2.png">

**Comment by breadnone** [comment]
bcos Fungus would expecting a Close markup if it detects the open-markup when DoWord gets executed. If it's for a PR, you can add your own condition just for that, I think

**Comment by addie-lombardo** [comment]
Closing this due to it working in the latest version of Fungus!

![new behaviour](https://user-images.githubusercontent.com/25385583/124183788-915cca80-da6d-11eb-96a9-3edf48b418f7.gif)
