### ISSUE TITLE
Newly Added Command Won't Auto Focused/Selected After Creation

### ISSUE THREAD

**Issue by breadnone** [snozbot/fungus#994]
**Describe the bug**
Newly added commands would not be focused after it gets created thus making it hard to search for it if we have many commands in that same block.

Another weird behavior, is that after the we clicked one of the command in inspector, then add new command, the newly added command would be placed under it (this is an expected behavior, from code) BUT if we add other commands after that, they would be placed at the most bottom order in that block which kinda weird.

**To Reproduce**
Add any new commands, and once added, the block inspector would be blank or out of focus.

**Expected behavior**
Should be automatically auto focus to the newly added commands

**Versions & Platform (please complete the following information):**
 - Unity version 2020 LTS

**Comment by Arylos07** [comment]
I'll look into this over the weekend. I made a patch for this at some point in my own copy so I'll try and merge that in.
